/**
 * INDIA — A LIVING CANVAS: ACROSS INDIA
 * Curated Geography Dataset of 30 Definitive Indian Art Locations
 * 100% Indian destinations with verified latitude/longitude coordinates,
 * authentic local/curated imagery, structured Art DNA, and 3-tier visual hierarchy.
 */

export const MAP_LOCATIONS = [
  // =========================================================================
  // WESTERN INDIA
  // =========================================================================
  {
    id: "ajanta-caves",
    name: "Ajanta Caves",
    state: "Maharashtra",
    region: "West",
    locationType: "monument",
    coordinates: { lat: 20.5519, lng: 75.7033 },
    hierarchy: "major",
    artForms: ["Painting", "Architecture", "Sculpture"],
    era: "Ancient",
    tradition: "Classical Buddhist Mural Painting",
    period: "2nd century BCE – 6th century CE",
    image: "assets/images/ajanta-cave-murals.jpg",
    thumb: "assets/images/ajanta-cave-murals.jpg",
    imageCredit: "Archaeological Survey of India / UNESCO World Heritage Centre",
    shortDescription: "Thirty rock-cut Buddhist cave monuments carved into a panoramic basalt gorge, holding the supreme classical masterworks of ancient Asian tempera mural painting.",
    historicalContext: "Excavated under the patronage of the Satavahanas and Vakatakas (notably King Harishena), Ajanta served as a monsoon sanctuary and university for Buddhist monks. The subterranean halls were painted by lamplight with natural lapis, malachite, and mineral ochres.",
    significance: "The foundational canon of Asian Buddhist painting, defining spiritual empathy, contour shading, and fluid narrative composition across South and East Asia.",
    keyFeatures: [
      "Bodhisattva Padmapani holding the sacred blue nilotpala lotus in Cave 1",
      "Continuous narrative depictions of the Jataka tales painted with natural fresco-secco glazes",
      "Monolithic Chaitya halls with horseshoe sun-windows (chandrashalas) and ribbed stone vaulting",
      "Supreme mastery of three-dimensional anatomy rendered purely through calligraphic line"
    ],
    didYouKnow: "Hidden for over a thousand years under thick jungle overgrowth, the caves were rediscovered in 1819 by British cavalry officer John Smith while hunting tigers.",
    artTrails: ["buddhist", "painting"]
  },
  {
    id: "ellora-kailasa",
    name: "Kailasa Temple, Ellora",
    state: "Maharashtra",
    region: "West",
    locationType: "monument",
    coordinates: { lat: 20.0268, lng: 75.1790 },
    hierarchy: "major",
    artForms: ["Architecture", "Sculpture"],
    era: "Medieval",
    tradition: "Rashtrakuta Monolithic Rock Architecture",
    period: "c. 760 – 800 CE",
    image: "assets/images/kailasa-temple-ellora.jpg",
    thumb: "assets/images/kailasa-temple-ellora.jpg",
    imageCredit: "Archaeological Survey of India / UNESCO World Heritage Centre",
    shortDescription: "The world's greatest monolithic excavation: an entire multi-storied temple complex carved top-down out of a single volcanic basalt mountain cliff.",
    historicalContext: "Commissioned primarily by the Rashtrakuta monarch Krishna I. Master masons removed more than 200,000 tonnes of basalt without mortar or scaffolding, carving temples, courtyards, obelisks, and life-size elephants directly from the cliff.",
    significance: "An unparalleled architectural feat of human engineering, conceived as a terrestrial replica of Mount Kailash, Lord Shiva’s cosmic mountain abode.",
    keyFeatures: [
      "Top-down vertical quarrying technique with zero margin for architectural error",
      "Monumental plinth supported by a continuous frieze of life-size elephants and lions",
      "Dramatically staged bas-relief of Ravana attempting to shake Mount Kailash",
      "Twin 50-foot free-standing monolithic victory pillars (dhvajastambhas)"
    ],
    didYouKnow: "Inscriptions record that upon viewing the finished monument, the master architect himself exclaimed in awe: 'Oh, how was it that I built this without an error?!'",
    artTrails: ["temple"]
  },
  {
    id: "elephanta-caves",
    name: "Elephanta Island Caves",
    state: "Maharashtra",
    region: "West",
    locationType: "monument",
    coordinates: { lat: 18.9633, lng: 72.9315 },
    hierarchy: "secondary",
    artForms: ["Sculpture", "Architecture"],
    era: "Classical",
    tradition: "Kalachuri & Konkan Shaivite Rock Cavities",
    period: "c. 5th – 6th century CE",
    image: "assets/images/hero-bg.jpg",
    thumb: "assets/images/hero-bg.jpg",
    imageCredit: "Archaeological Survey of India / UNESCO World Heritage Centre",
    shortDescription: "A labyrinth of rock-cut temple halls on an island in Mumbai harbor, home to the colossal 20-foot Sadashiva Trimurti bust.",
    historicalContext: "Carved under the Kalachuri dynasty, Elephanta island (historically Gharapuri) served as a maritime sacred center where merchant ships honored Lord Shiva before venturing across the Arabian Sea.",
    significance: "Celebrated for the profound philosophical synthesis of Shiva as Creator, Preserver, and Destroyer embodied in a single colossal trinity.",
    keyFeatures: [
      "Colossal 20-foot three-headed Sadashiva representing Aghora (wrath), Tatpurusha (serenity), and Vamadeva (gentleness)",
      "High-relief carvings of Shiva Ardhanarishvara (half-man, half-woman divine balance)",
      "Pillared hypostyle cave mandapa featuring monumental cushioned capitals",
      "Dynamic narrative tableau of Gangadhara catching the sacred river Ganga in his matted locks"
    ],
    didYouKnow: "16th-century Portuguese sailors named the island 'Elephanta' after encountering a colossal stone elephant statue standing near the shore.",
    artTrails: ["temple"]
  },
  {
    id: "warli-region",
    state: "Maharashtra",
    name: "Warli Tribal Region (Dahanu & Palghar)",
    region: "West",
    locationType: "region",
    coordinates: { lat: 19.9700, lng: 72.7300 },
    hierarchy: "secondary",
    artForms: ["Folk & Tribal"],
    era: "Contemporary",
    tradition: "Indigenous Adivasi Wall Painting",
    period: "Ancient Origins to Living Contemporary Tradition",
    image: "assets/images/folk-tribal-traditions.jpg",
    thumb: "assets/images/folk-tribal-traditions.jpg",
    imageCredit: "Crafts Museum, New Delhi / National Handicrafts Centre",
    shortDescription: "Ancient living vernacular art form celebrating the sacred harmony between tribal humanity, spirits, and nature through elemental geometric symbols.",
    historicalContext: "Created by the Warli indigenous community nestled along the northern Western Ghats. Traditionally painted by suvasinis (married women) on the mud-plastered walls of wedding huts using chewed bamboo sticks and rice paste.",
    significance: "Represents an unadulterated Neolithic artistic grammar that eschews perspective for spiritual rhythm, communal solidarity, and cosmic ecology.",
    keyFeatures: [
      "Elemental visual language based on basic geometric archetypes: circles (sun/moon), triangles (trees/mountains), and squares (sacred space)",
      "Iconic spiraling Tarpa dance circles where villagers dance in harmony around a central musician",
      "Central sacred square (Chauk) enshrining Palaghata, the goddess of fertility and corn",
      "Use of natural rice paste mixed with water and binding gum on red ochre mud walls"
    ],
    didYouKnow: "Warli art was brought to the global contemporary stage in the 1970s by master artist Jivya Soma Mashe, who was honored with the Padma Shri.",
    artTrails: ["folk"]
  },
  {
    id: "kishangarh-jaipur",
    name: "Kishangarh & Jaipur",
    state: "Rajasthan",
    region: "West",
    locationType: "city",
    coordinates: { lat: 26.5744, lng: 74.8643 },
    hierarchy: "major",
    artForms: ["Painting", "Miniature"],
    era: "Early Modern",
    tradition: "Rajput Miniature Court Painting",
    period: "17th – 18th century CE",
    image: "assets/images/bani-thani-kishangarh.jpg",
    thumb: "assets/images/bani-thani-kishangarh.jpg",
    shortDescription: "The lyrical crown of Rajasthani court art, celebrated for Nihal Chand's poetic Radha portrait (Bani Thani) and luminous Krishna devotion.",
    historicalContext: "Flourishing under the enlightened patronage of Raja Savant Singh (the poet-king Nagari Das) in Kishangarh and the royal atelier of Maharaja Sawai Jai Singh II in Jaipur.",
    significance: "Pioneered a hyperbolic aesthetic canon characterized by lotus-petal eyes, arched brows, and diaphanous golden veils, often called the 'Mona Lisa of India'.",
    keyFeatures: [
      "Exaggerated, sharply curved almond eyes (kamal-nayan) and delicate pointed chins",
      "Gossamer gold-sprigged translucent veils (odhnis) framing aristocratic profiles",
      "Lyrical nocturnal court scenes illuminated by silver lakes and marble pavilions",
      "Mineral pigments ground from crushed pearls, lapis lazuli, and 24-karat gold leaf"
    ],
    didYouKnow: "Bani Thani ('the adorned one') was a gifted poet and singer at the royal court whose elegance inspired the entire Kishangarh style.",
    artTrails: ["painting"]
  },
  {
    id: "nathdwara",
    name: "Nathdwara",
    state: "Rajasthan",
    region: "West",
    locationType: "city",
    coordinates: { lat: 24.9318, lng: 73.8222 },
    hierarchy: "secondary",
    artForms: ["Painting", "Folk & Tribal"],
    era: "Early Modern",
    tradition: "Pichwai Temple Textile Painting",
    period: "17th century CE to Present",
    image: "assets/images/bani-thani-kishangarh.jpg",
    thumb: "assets/images/bani-thani-kishangarh.jpg",
    imageCredit: "Shrinathji Temple Trust / Government of Rajasthan Tourism",
    shortDescription: "Sacred town renowned for monumental Pichwai paintings—luxurious hand-painted cloth backdrops depicting Lord Krishna as Shrinathji.",
    historicalContext: "Originated when the sacred 14th-century black marble deity of Shrinathji was installed in Nathdwara in 1672 to protect it during Mughal campaigns. Hereditary artisan guilds of the Pushtimarg sect created painted backdrops for each daily ritual and season.",
    significance: "One of India's richest continuous liturgical textile traditions, weaving seasonal moods, blooming lotuses, and sacred cows into devotional visual poetry.",
    keyFeatures: [
      "Intricate hand-painted starched cotton fabrics hung behind the temple sanctum",
      "Sharad Purnima (autumn full moon) and Janmashtami festival narrative scenes",
      "Iconic herds of stylized cows (Gowalas) adorned with handprints and peacock feathers",
      "Lush groves of kadamba trees filled with pairs of dancing peacocks"
    ],
    didYouKnow: "A single large Pichwai cloth can take a master artist over six months to paint using squirrel-hair brushes and pure gold leaf paste.",
    artTrails: ["painting", "folk"]
  },

  // =========================================================================
  // CENTRAL INDIA
  // =========================================================================
  {
    id: "bhimbetka-caves",
    name: "Bhimbetka Rock Shelters",
    state: "Madhya Pradesh",
    region: "Central",
    locationType: "site",
    coordinates: { lat: 22.9372, lng: 77.6127 },
    hierarchy: "major",
    artForms: ["Painting"],
    era: "Ancient",
    tradition: "Prehistoric Mesolithic Rock Art",
    period: "c. 10,000 – 8,000 BCE",
    image: "assets/images/bhimbetka-rock-art.jpg",
    thumb: "assets/images/bhimbetka-rock-art.jpg",
    imageCredit: "Archaeological Survey of India / UNESCO World Heritage Centre",
    shortDescription: "Over 750 prehistoric rock shelters nestled in sandstone cliffs, preserving 10,000 years of unbroken human visual expression.",
    historicalContext: "Discovered by archaeologist Dr. V.S. Wakankar in 1957. The paintings reveal the daily lives, communal ceremonies, animal veneration, and hunting rituals of early hunter-gatherers across the Vindhyan range.",
    significance: "The oldest visual record of human existence on the Indian subcontinent, designated a UNESCO World Heritage Site.",
    keyFeatures: [
      "Dynamic red haematite and manganese stick figures showing horsemen and hunters",
      "Superimposed multi-layered painting styles spanning Upper Paleolithic to Medieval times",
      "Realistic animal portraits of gaur, tigers, wild boars, and horned rhinos",
      "Scenes of communal dance, ritual processions, and maternal tenderness"
    ],
    didYouKnow: "The red pigment (geru) utilized natural iron oxides that reacted chemically with the sandstone, allowing paintings to survive exposed monsoons for over 100 centuries.",
    artTrails: ["buddhist", "folk"]
  },
  {
    id: "sanchi-stupa",
    name: "The Great Stupa at Sanchi",
    state: "Madhya Pradesh",
    region: "Central",
    locationType: "monument",
    coordinates: { lat: 23.4794, lng: 77.7397 },
    hierarchy: "major",
    artForms: ["Architecture", "Sculpture"],
    era: "Ancient",
    tradition: "Early Buddhist Torana Narrative Carving",
    period: "c. 2nd century BCE – 1st century CE",
    image: "assets/images/sanchi-great-stupa.jpg",
    thumb: "assets/images/sanchi-great-stupa.jpg",
    imageCredit: "Archaeological Survey of India / UNESCO World Heritage Centre",
    shortDescription: "The crown jewel of early Buddhist commemorative architecture, renowned for its four monumental stone ceremonial gateways (Toranas).",
    historicalContext: "Originally commissioned by Emperor Ashoka over the relics of Gautama Buddha. The Satavahanas later added the four monumental Toranas carved by the ivory carvers' guild of nearby Vidisha.",
    significance: "Presents the earliest panoramic visual encyclopedia of the Jataka tales depicted through aniconic Buddhist symbols (empty throne, parasol, wheel).",
    keyFeatures: [
      "Four monumental carved gateways teeming with continuous narrative bas-reliefs",
      "Famous bracket figures of voluptuous Yakshis swinging gracefully from mango boughs",
      "Solid hemispherical stone dome (anda) crowned by harmika railing and triple umbrella (chhatra)",
      "Raised circumambulatory path (pradakshina patha) for mindful clockwise walking meditation"
    ],
    didYouKnow: "Inscriptions on the gateway pillars reveal that ordinary citizen guilds—including the local guild of ivory carvers—sponsored and carved sections of the stone, explaining the astonishing jewelry-like micro-detail.",
    artTrails: ["buddhist", "temple"]
  },
  {
    id: "khajuraho-monuments",
    name: "Khajuraho Group of Monuments",
    state: "Madhya Pradesh",
    region: "Central",
    locationType: "monument",
    coordinates: { lat: 24.8318, lng: 79.9199 },
    hierarchy: "major",
    artForms: ["Architecture", "Sculpture"],
    era: "Medieval",
    tradition: "Chandela Nagara Sandhara Architecture",
    period: "c. 950 – 1050 CE",
    image: "assets/images/khajuraho-kandariya-mahadeva.jpg",
    thumb: "assets/images/khajuraho-kandariya-mahadeva.jpg",
    imageCredit: "Archaeological Survey of India / UNESCO World Heritage Centre",
    shortDescription: "The architectural zenith of the Northern Nagara temple style, famed for its soaring mountain-like spires and over 800 celestial figures carved into golden sandstone.",
    historicalContext: "Built by the powerful Chandela dynasty monarchs like Vidyadhara. Out of the original 85 temples, 25 survive, honoring Shiva, Vishnu, and Jain Tirthankaras in harmonic tolerance.",
    significance: "Celebrated globally for supreme sculptural fluidity and psychological vitality, portraying divine cosmos, celestial maidens (Surasundaris), and loving couples in sacred harmony.",
    keyFeatures: [
      "Soaring Kandariya Mahadeva shikhara composed of 84 miniature replica spires (urushringas)",
      "Exquisite Surasundaris depicted applying eye kohl, removing thorns, and playing flutes",
      "Precision dry-stone tongue-and-groove masonry constructed without a single drop of mortar",
      "Tantric decorative panels placed at wall junctions to symbolize divine cosmic equilibrium"
    ],
    didYouKnow: "Despite modern popular misconceptions, erotic sculptures account for less than 10% of Khajuraho's stone carvings; the rest portray civic life, music, and celestial devotion.",
    artTrails: ["temple"]
  },
  {
    id: "gond-region",
    name: "Gond Art Region (Dindori & Bhopal)",
    state: "Madhya Pradesh",
    region: "Central",
    locationType: "region",
    coordinates: { lat: 23.2599, lng: 77.4126 },
    hierarchy: "secondary",
    artForms: ["Folk & Tribal", "Painting"],
    era: "Contemporary",
    tradition: "Pardhan Gond Sacred Mythological Art",
    period: "Ancient Origins to Contemporary Renaissance",
    image: "assets/images/folk-tribal-traditions.jpg",
    thumb: "assets/images/folk-tribal-traditions.jpg",
    imageCredit: "Bharat Bhavan Bhopal / Tribal Museum of Madhya Pradesh",
    shortDescription: "Vibrant indigenous tribal painting tradition that translates oral mythologies, ancestral spirits, and forest ecology into luminous patterned line work.",
    historicalContext: "Originated among the Pardhan Gond bards of the Satpura forests who recounted genealogical epics (Bana). In the 1980s, master pioneer Jangarh Singh Shyam transposed this art onto canvas at Bharat Bhavan, founding the 'Jangarh Kalam' movement.",
    significance: "An acclaimed contemporary Indigenous art movement celebrated in major museums worldwide for its rhythmic stippled dot-and-line textures and vibrant mythic imagination.",
    keyFeatures: [
      "Distinctive signature fill patterns: each artist develops unique micro-patterns of dots, dashes, or scales",
      "Depiction of sacred trees (Mahua, Saja) connecting earth, water, and spirit worlds",
      "Hybrid mythical animals: winged birds with deer horns, flying serpents, and celestial bulls",
      "Use of brilliant natural and acrylic colors: turmeric yellow, cinnabar red, and forest blues"
    ],
    didYouKnow: "In Gond belief, viewing a good painting brings auspicious fortune and guards the home against malevolent forest spirits.",
    artTrails: ["folk"]
  },
  {
    id: "bastar-region",
    name: "Bastar Dhokra Craft Region",
    state: "Chhattisgarh",
    region: "Central",
    locationType: "region",
    coordinates: { lat: 19.0700, lng: 82.0300 },
    hierarchy: "secondary",
    artForms: ["Sculpture", "Folk & Tribal"],
    era: "Contemporary",
    tradition: "Dhokra Lost-Wax Bell Metal Metallurgy",
    period: "4,000-year continuous metallurgy lineage",
    image: "assets/images/dancing-girl-mohenjodaro.jpg",
    thumb: "assets/images/dancing-girl-mohenjodaro.jpg",
    imageCredit: "Bastar Craft Council / Ministry of Textiles, Govt. of India",
    shortDescription: "Centuries-old lost-wax metallurgy practiced by tribal metalsmiths (Ghadwas) of Bastar, crafting rustic bronze icons of deities, deer, and elephants.",
    historicalContext: "Direct living metallurgical heir to the Indus Valley Dancing Girl casting technique. Artisan families construct clay cores, wrap them in wax threads, encase them in river clay molds, and pour molten bell metal over fire pits.",
    significance: "A world-renowned non-ferrous metal casting heritage recognized with Geographical Indication (GI) status.",
    keyFeatures: [
      "Intricate spiral wirework effect achieved by winding fine beeswax strands around a clay core",
      "Elongated, primitive tribal proportions capturing movement and spiritual grace",
      "Depictions of village deities: Danteshwari, Pardesi Mata, war horses, and ritual lamps (diyas)",
      "Rough antique golden brass-bronze patina burnished by hand"
    ],
    didYouKnow: "The wax used in the casting process is pure wild beeswax collected by tribal gatherers from the deep sal forests of Bastar.",
    artTrails: ["folk"]
  },

  // =========================================================================
  // EASTERN INDIA
  // =========================================================================
  {
    id: "konark-temple",
    name: "Sun Temple at Konark",
    state: "Odisha",
    region: "East",
    locationType: "monument",
    coordinates: { lat: 19.8876, lng: 86.0945 },
    hierarchy: "major",
    artForms: ["Architecture", "Sculpture"],
    era: "Medieval",
    tradition: "Kalinga Monumental Chariot Architecture",
    period: "c. 1250 CE",
    image: "assets/images/konark-sun-temple.jpg",
    thumb: "assets/images/konark-sun-temple.jpg",
    imageCredit: "Archaeological Survey of India / UNESCO World Heritage Centre",
    shortDescription: "Conceived as a colossal stone chariot with 24 giant intricately carved wheels drawn by seven galloping horses for Surya, the Sun God.",
    historicalContext: "Built by King Narasimhadeva I of the Eastern Ganga dynasty along the shores of the Bay of Bengal. European mariners called it the 'Black Pagoda' because its dark khondalite stone served as a navigational landmark.",
    significance: "The architectural summit of the Kalinga style, praised for mathematical sundial accuracy and peerless monumental sculpture.",
    keyFeatures: [
      "Twenty-four stone wheels, each 10 feet in diameter, functioning as accurate astronomical sundials",
      "Seven rearing horses carved into the plinth symbolizing the seven days of the week and light rays",
      "Monumental base friezes depicting imperial war parades, elephant hunts, and court musicians",
      "Green chlorite statues of the Sun God standing on his celestial carriage"
    ],
    didYouKnow: "The spokes of the 24 Konark wheels act as sundials; the shadow cast by the central hub on the carved spoke beads indicates the exact time of day to within minutes.",
    artTrails: ["temple"]
  },
  {
    id: "raghurajpur-puri",
    name: "Raghurajpur & Puri",
    state: "Odisha",
    region: "East",
    locationType: "city",
    coordinates: { lat: 19.8400, lng: 85.8200 },
    hierarchy: "secondary",
    artForms: ["Painting", "Folk & Tribal"],
    era: "Medieval",
    tradition: "Odisha Pattachitra & Palm Leaf Engraving",
    period: "12th century CE to Present",
    image: "assets/images/folk-tribal-traditions.jpg",
    thumb: "assets/images/folk-tribal-traditions.jpg",
    imageCredit: "Odisha State Museum / Raghurajpur Heritage Craft Village",
    shortDescription: "Heritage craft village where every household preserves the sacred Pattachitra painting tradition on cotton cloth and palm leaves (Tala Pattachitra).",
    historicalContext: "Deeply entwined with the worship of Lord Jagannath in Puri. When the deities are ritually secluded for 15 days before the annual Rath Yatra (Anavasara period), traditional Pattachitra paintings (Anasarapatti) take their place in the inner sanctum.",
    significance: "India's first declared Heritage Crafts Village, renowned for fine calligraphic lines, natural stone pigments, and palm leaf incised manuscripts.",
    keyFeatures: [
      "Canvas prepared by bonding layers of cotton cloth with tamarind seed paste and chalk powder",
      "Brilliant pigments made from conch shell white, hingula red, haritala yellow, and lampblack",
      "Detailed narrative borders framing Jagannath Triad, Gita Govinda, and Dashavatara episodes",
      "Delicate Tala Pattachitra: etched with iron styluses onto dried palm leaves and inked with soot"
    ],
    didYouKnow: "The iconic Odissi classical dance legend Guru Kelucharan Mohapatra was born in Raghurajpur and trained as a traditional Gotipua dancer and patta painter here.",
    artTrails: ["painting", "folk"]
  },
  {
    id: "bhubaneswar",
    name: "Bhubaneswar Temple City",
    state: "Odisha",
    region: "East",
    locationType: "city",
    coordinates: { lat: 20.2405, lng: 85.8340 },
    hierarchy: "secondary",
    artForms: ["Architecture", "Sculpture"],
    era: "Classical",
    tradition: "Classical Kalinga Nagara Architecture",
    period: "7th – 12th century CE",
    image: "assets/images/konark-sun-temple.jpg",
    thumb: "assets/images/konark-sun-temple.jpg",
    imageCredit: "Archaeological Survey of India / Odisha Tourism",
    shortDescription: "The ancient 'City of Temples' showcasing the evolutionary progression of Kalinga architecture from the jewel-box Mukteshvara to the soaring Lingaraja.",
    historicalContext: "Flourishing under the Somavamshi and Eastern Ganga dynasties. Once boasted over 1,000 stone temples clustered around the sacred Bindusagar lake.",
    significance: "Presents the complete textbook sequence of North Indian curvilinear shikhara (Rekha Deula) and pyramidal porch (Pidha Deula) temple morphology.",
    keyFeatures: [
      "The 10th-century Mukteshvara Temple, praised as the 'gem of Odishan architecture' with its ornate carved stone torana archway",
      "Lingaraja Temple’s majestic 180-foot soaring sanctum tower dominating the sacred skyline",
      "Intricately carved Parsvadevatas, celestial dancers, and foliage panels in red sandstone",
      "Rajarani Temple’s warm amber sandstone friezes depicting graceful nayikas"
    ],
    didYouKnow: "The Mukteshvara torana gateway exhibits distinct Buddhist and Jain stylistic influences, reflecting the syncretic spiritual harmony of ancient Kalinga.",
    artTrails: ["temple"]
  },
  {
    id: "mithila-madhubani",
    name: "Mithila & Madhubani",
    state: "Bihar",
    region: "East",
    locationType: "region",
    coordinates: { lat: 26.3500, lng: 86.0800 },
    hierarchy: "major",
    artForms: ["Folk & Tribal", "Painting"],
    era: "Contemporary",
    tradition: "Mithila Ceremonial Painting",
    period: "Ancient Origins to Living Contemporary Tradition",
    image: "assets/images/folk-tribal-traditions.jpg",
    thumb: "assets/images/folk-tribal-traditions.jpg",
    imageCredit: "Mithila Museum / Crafts Museum New Delhi",
    shortDescription: "Centuries-old domestic and ritual art practiced by rural women on cow-dung plastered mud walls, renowned for double-line contours and hatching.",
    historicalContext: "Mythologically traced to King Janaka commissioning painters to decorate Mithila for the wedding of Sita and Lord Rama. Preserved by women across generations in the villages of Ranti and Jitwarpur.",
    significance: "One of India's most internationally recognized folk traditions, distinguished by distinct stylistic sub-genres: Bharni, Kachni, Tantrik, and Godna.",
    keyFeatures: [
      "Intricate double-line outlines filled with fine cross-hatching and vibrant mineral dyes",
      "Kohbar wedding chamber murals depicting symbols of cosmic fertility: lotus, fish, bamboo, and turtles",
      "Complete avoidance of empty space (horror vacui): every inch filled with birds, flowers, or geometric motifs",
      "Natural pigments derived from crushed berries, turmeric, indigo, soot, and tree saps"
    ],
    didYouKnow: "After the devastating 1934 Bihar earthquake destroyed village homes, British civil servant William G. Archer uncovered the stunning interior murals and introduced them to the world.",
    artTrails: ["folk", "painting"]
  },
  {
    id: "nalanda",
    name: "Nalanda Mahavihara",
    state: "Bihar",
    region: "East",
    locationType: "monument",
    coordinates: { lat: 25.1357, lng: 85.4437 },
    hierarchy: "secondary",
    artForms: ["Architecture", "Sculpture"],
    era: "Classical",
    tradition: "Pala Buddhist Bronzes & Monastic Brick Architecture",
    period: "5th – 12th century CE",
    image: "assets/images/sarnath-gupta-buddha.jpg",
    thumb: "assets/images/sarnath-gupta-buddha.jpg",
    imageCredit: "Archaeological Survey of India / UNESCO World Heritage Centre",
    shortDescription: "The world's premier ancient residential monastic university, famed for its towering brick stupas and the celebrated Pala school of bronze casting.",
    historicalContext: "Founded under the Gupta Empire and lavishly patronized by King Harshavardhana and the Pala emperors. Housed over 10,000 scholars from China, Korea, Tibet, and Central Asia.",
    significance: "The intellectual fountainhead of Vajrayana Buddhism, exporting artistic canons and lost-wax bronze techniques to Tibet, Nepal, and Southeast Asia.",
    keyFeatures: [
      "Colossal Sariputta Stupa (Site 3) featuring multi-layered brick terraces adorned with Gupta terracotta niches",
      "Exquisite Pala cast bronze statues of Tara, Avalokiteshvara, and Manjushri with silver inlays",
      "Systematic architectural layout with lecture halls, dormitories, meditation cells, and brick water wells",
      "Pala black basalt stone stelae carved with intricate flaming halos and Tantric iconography"
    ],
    didYouKnow: "When Chinese pilgrim Xuanzang studied at Nalanda in the 7th century, he recorded that the university's Dharmaganja library consisted of three multi-story towers named Ratnasagara, Ratnodadhi, and Ratnaranjaka.",
    artTrails: ["buddhist"]
  },
  {
    id: "kolkata-santiniketan",
    name: "Kolkata & Santiniketan",
    state: "West Bengal",
    region: "East",
    locationType: "city",
    coordinates: { lat: 22.5726, lng: 88.3639 },
    hierarchy: "major",
    artForms: ["Painting", "Modern"],
    era: "Modern",
    tradition: "Bengal School of Art & Swadeshi Renaissance",
    period: "c. 1900 – 1940s CE",
    image: "assets/images/bengal-school-bharat-mata.jpg",
    thumb: "assets/images/bengal-school-bharat-mata.jpg",
    imageCredit: "National Gallery of Modern Art, New Delhi / Victoria Memorial Hall",
    shortDescription: "The epicenter of India's nationalist modern art renaissance, where Abanindranath Tagore, Nandalal Bose, and Rabindranath Tagore forged a modern Pan-Asian aesthetic.",
    historicalContext: "Founded as an ideological resistance to Western academic realism during the 1905 anti-partition protests in Kolkata. Later evolved at Rabindranath Tagore’s open-air university Kala Bhavana in Santiniketan.",
    significance: "Asserted India's cultural independence by harmonizing classical Ajanta aesthetics, Mughal fine line, and Japanese wet-on-wet wash methods.",
    keyFeatures: [
      "Abanindranath Tagore's iconic 1905 'Bharat Mata' personifying Mother India as an ascetic maiden",
      "Luminous, dreamy atmospheric haze created through repeated immersions in water basins (Japanese wash technique)",
      "Nandalal Bose's public linocuts and original hand-illustrated panels of the Constitution of India",
      "Ramkinkar Baij’s monumental open-air outdoor concrete sculptures of Santhal tribal families"
    ],
    didYouKnow: "Kala Bhavana at Santiniketan was India's first modern art institution to embrace tribal and rural crafts as equals alongside classical fine art.",
    artTrails: ["painting"]
  },
  {
    id: "bishnupur-terracotta",
    name: "Bishnupur",
    state: "West Bengal",
    region: "East",
    locationType: "city",
    coordinates: { lat: 23.0678, lng: 87.3175 },
    hierarchy: "secondary",
    artForms: ["Architecture", "Sculpture"],
    era: "Early Modern",
    tradition: "Malla Terracotta Temple Architecture",
    period: "17th – 18th century CE",
    image: "assets/images/bengal-school-bharat-mata.jpg",
    thumb: "assets/images/bengal-school-bharat-mata.jpg",
    imageCredit: "Archaeological Survey of India / West Bengal Tourism",
    shortDescription: "Capital of the Malla kings, renowned for its distinctive baked-earth terracotta temples featuring curved thatched-hut (chala) rooflines.",
    historicalContext: "Built by the devout Vaishnava Malla rulers in the alluvial Bengal delta where building stone was scarce. Masons transformed local clay into dense, exquisitely carved terracotta relief tiles.",
    significance: "The definitive masterwork of regional Bengali temple architecture, creating the iconic 'Chala' and 'Ratna' styles later copied in colonial bungalows.",
    keyFeatures: [
      "Distinctive curved cornices mimicking the flexible bamboo eaves of rural Bengali thatched huts (Bangla chala)",
      "Facade walls blanketed with thousands of carved terracotta narrative tiles illustrating the Ramayana and Krishna Leela",
      "Monumental Rasmancha: unique pyramidal stepped brick pavilion designed for seasonal festival deities",
      "Famous high-necked Terracotta Bankura Horses crafted by local Kumbhakar potter guilds"
    ],
    didYouKnow: "The curved 'Bangla' roof pioneered in Bishnupur temples was so admired by Mughal Emperor Shah Jahan that he incorporated it into the imperial pavilions of the Agra and Delhi forts.",
    artTrails: ["temple", "folk"]
  },

  // =========================================================================
  // SOUTHERN INDIA
  // =========================================================================
  {
    id: "thanjavur",
    name: "Thanjavur (Tanjore)",
    state: "Tamil Nadu",
    region: "South",
    locationType: "city",
    coordinates: { lat: 10.7828, lng: 79.1318 },
    hierarchy: "major",
    artForms: ["Architecture", "Sculpture", "Painting"],
    era: "Medieval",
    tradition: "Imperial Chola Architecture & Tanjore Gold Leaf Painting",
    period: "10th – 19th century CE",
    image: "assets/images/tanjore-gold-leaf-painting.jpg",
    thumb: "assets/images/tanjore-gold-leaf-painting.jpg",
    imageCredit: "Archaeological Survey of India / Government Museum Chennai",
    shortDescription: "The imperial capital of the Cholas, home to the monumental Brihadisvara Temple and the dazzling, gemstone-encrusted Tanjore gold foil painting tradition.",
    historicalContext: "Rajaraja Chola I built the colossal Big Temple in 1010 CE. Centuries later under the Maratha rulers like Serfoji II, migrant Raju and Naidu artisans developed the gilded Tanjore painting school.",
    significance: "The dual heart of South Indian monumental Dravidian stone architecture and sacred devotional painting on teakwood boards.",
    keyFeatures: [
      "Brihadisvara Temple's soaring 216-foot stone vimana crowned by an 80-tonne monolithic granite dome",
      "Tanjore paintings crafted with embossed gesso limestone relief, 22K gold leaf, and Jaipur gemstones",
      "Ancient Chola lost-wax bronze foundry traditions casting the cosmic Nataraja and Parvati statues",
      "Celebrated Chola wall murals discovered in the circumambulatory corridor of the Big Temple sanctum"
    ],
    didYouKnow: "The 80-tonne granite capstone of Brihadisvara was rolled to the top of the 216-foot tower using a massive earthen ramp stretching over 6 kilometers from the village of Sarapallam.",
    artTrails: ["temple", "painting"]
  },
  {
    id: "mamallapuram",
    name: "Mamallapuram (Mahabalipuram)",
    state: "Tamil Nadu",
    region: "South",
    locationType: "monument",
    coordinates: { lat: 12.6269, lng: 80.1927 },
    hierarchy: "major",
    artForms: ["Sculpture", "Architecture"],
    era: "Classical",
    tradition: "Pallava Monolithic Granite Architecture & Bas-Relief",
    period: "c. 7th – 8th century CE",
    image: "assets/images/descent-of-the-ganges.jpg",
    thumb: "assets/images/descent-of-the-ganges.jpg",
    imageCredit: "Archaeological Survey of India / UNESCO World Heritage Centre",
    shortDescription: "An ancient seaport of the Pallava dynasty, renowned for open-air monolithic rock-cut rathas, cave temples, and the Shore Temple overlooking the ocean.",
    historicalContext: "Commissioned by King Narasimhavarman I (Mamalla) along the Coromandel coast. The coastal cliffs were sculpted into an open-air theatrical laboratory of Dravidian temple prototypes.",
    significance: "The birthplace of South Indian Dravidian stone temple architecture, featuring the world's largest open-air monolithic rock bas-relief (Descent of the Ganges).",
    keyFeatures: [
      "Descent of the Ganges (Arjuna's Penance): colossal 96-foot relief carved across two natural granite boulders",
      "Pancha Rathas: five monolithic chariot-temples carved out of a single granite outcrop",
      "Shore Temple: structural stone masterpiece standing resilient against coastal salt winds for 1,300 years",
      "Lively animal studies: life-size elephants, playful monkey families, and the meditating cat"
    ],
    didYouKnow: "The 2004 Indian Ocean tsunami briefly pulled the sea back 500 meters at Mamallapuram, momentarily exposing submerged stone structures of the fabled 'Seven Pagodas'.",
    artTrails: ["temple"]
  },
  {
    id: "madurai",
    name: "Madurai Meenakshi Amman",
    state: "Tamil Nadu",
    region: "South",
    locationType: "monument",
    coordinates: { lat: 9.9195, lng: 78.1193 },
    hierarchy: "major",
    artForms: ["Architecture", "Sculpture"],
    era: "Early Modern",
    tradition: "Late Dravidian Nayaka Temple Architecture",
    period: "16th – 17th century CE",
    image: "assets/images/chola-nataraja-bronze.jpg",
    thumb: "assets/images/chola-nataraja-bronze.jpg",
    imageCredit: "Meenakshi Sundareswarar Temple Administration / Tamil Nadu Tourism",
    shortDescription: "The pulsing cultural soul of Tamil Nadu: a monumental temple city featuring 14 soaring multi-tiered gopurams encrusted with thousands of brightly painted stucco deities.",
    historicalContext: "Rebuilt and expanded to monumental scale under the Nayaka rulers, notably King Tirumala Nayaka (1623–1659). Conceived as a cosmic mandala city radiating outwards in concentric rectangular streets.",
    significance: "The supreme manifestation of late Dravidian architectural theatricality, famed for its Hall of Thousand Pillars and musical stone columns.",
    keyFeatures: [
      "Fourteen monumental gateway towers (gopurams), the tallest rising 170 feet with 1,511 polychrome stucco figures",
      "Hall of Thousand Pillars (Aayiram Kaal Mandapam) featuring 985 exquisitely carved granite warrior and divine pillars",
      "Famous musical stone pillars that resonate with distinct musical swaras when tapped",
      "Sacred Golden Lotus Tank (Porthamarai Kulam) where ancient Tamil Sangam poets evaluated literature"
    ],
    didYouKnow: "Madurai is one of the oldest continuously inhabited cities in the world, having traded pearls and fine spices with ancient Imperial Rome over 2,000 years ago.",
    artTrails: ["temple"]
  },
  {
    id: "kanchipuram",
    name: "Kanchipuram",
    state: "Tamil Nadu",
    region: "South",
    locationType: "city",
    coordinates: { lat: 12.8342, lng: 79.7036 },
    hierarchy: "secondary",
    artForms: ["Architecture", "Sculpture", "Folk & Tribal"],
    era: "Classical",
    tradition: "Pallava Stone Architecture & Pure Mulberry Silk Weaving",
    period: "8th century CE to Present",
    image: "assets/images/descent-of-the-ganges.jpg",
    thumb: "assets/images/descent-of-the-ganges.jpg",
    imageCredit: "Archaeological Survey of India / Tamil Nadu Handlooms",
    shortDescription: "One of India's seven sacred cities (Sapta Puri), celebrated for the 8th-century Kailasanathar Temple and centuries-old heavy mulberry silk handlooms.",
    historicalContext: "The imperial capital of the Pallavas. King Rajasimha Pallava constructed the sandstone Kailasanathar Temple in 700 CE. Later flourished as a global silk weaving center patronized by Cholas and Vijayanagara emperors.",
    significance: "The oldest structural stone temple in Tamil Nadu, setting the standard for all subsequent Dravidian vimana architecture and pure gold-zari silk weaving.",
    keyFeatures: [
      "Kailasanathar Temple: sandstone shrine with 58 small surrounding sub-shrines and dynamic lion-based pillars (yalis)",
      "Remnants of 8th-century classical Pallava fresco paintings in the circumambulatory niches",
      "Kanchipuram silk sarees hand-woven with pure silver and gold zari threads in korvai interlocking borders",
      "Vaikuntha Perumal Temple featuring multi-tiered sanctums and narrative dynastic inscription panels"
    ],
    didYouKnow: "Chalukya King Vikramaditya II, after conquering Kanchipuram in war, was so spellbound by the beauty of Kailasanathar Temple that he spared the city and brought its architects back to build the Virupaksha Temple in Pattadakal.",
    artTrails: ["temple"]
  },
  {
    id: "hampi-vijayanagara",
    name: "Hampi (Vijayanagara)",
    state: "Karnataka",
    region: "South",
    locationType: "monument",
    coordinates: { lat: 15.3350, lng: 76.4600 },
    hierarchy: "major",
    artForms: ["Architecture", "Sculpture"],
    era: "Medieval",
    tradition: "Vijayanagara Imperial Granite Architecture",
    period: "14th – 16th century CE",
    image: "assets/images/chola-nataraja-bronze.jpg",
    thumb: "assets/images/chola-nataraja-bronze.jpg",
    imageCredit: "Archaeological Survey of India / UNESCO World Heritage Centre",
    shortDescription: "The magnificent boulder-strewn capital ruins of the Vijayanagara Empire along the Tungabhadra River, famed for its stone chariot and musical pillars.",
    historicalContext: "Founded in 1336 by Harihara and Bukka, Hampi grew under Emperor Krishnadevaraya to become the second-largest city in the medieval world, visited by Portuguese, Persian, and Italian emissaries.",
    significance: "A UNESCO World Heritage Site celebrating the golden age of South Indian granite craftsmanship, blending indigenous Dravidian styles with Indo-Islamic courtly forms.",
    keyFeatures: [
      "Vittala Temple Stone Chariot: iconic monolithic shrine carved to resemble a processional festival chariot",
      "Fifty-six musical pillars carved from single granite blocks that emit varied musical tones",
      "Virupaksha Temple: towering 160-foot stepped entrance gopuram operating continuously since the 7th century",
      "Lotus Mahal and Elephant Stables showcasing sophisticated Indo-Islamic vaulted arches and domes"
    ],
    didYouKnow: "Portuguese traveler Domingo Paes wrote in 1520 that Hampi was 'as large as Rome, and very beautiful to the sight... the streets are so broad that a hundred men can ride abreast.'",
    artTrails: ["temple"]
  },
  {
    id: "badami-pattadakal",
    name: "Badami & Pattadakal",
    state: "Karnataka",
    region: "South",
    locationType: "site",
    coordinates: { lat: 15.9189, lng: 75.6798 },
    hierarchy: "secondary",
    artForms: ["Architecture", "Sculpture"],
    era: "Classical",
    tradition: "Early Chalukya Rock-Cut & Structural Synthesis",
    period: "6th – 8th century CE",
    image: "assets/images/kailasa-temple-ellora.jpg",
    thumb: "assets/images/kailasa-temple-ellora.jpg",
    imageCredit: "Archaeological Survey of India / UNESCO World Heritage Centre",
    shortDescription: "Red sandstone cliff canyons where Early Chalukya rulers harmonized northern Nagara and southern Dravidian architectural idioms.",
    historicalContext: "The Chalukyan capital (Vatapi). Pattadakal served as the ceremonial coronation site along the Malaprabha River where royal architects actively cross-pollinated building traditions.",
    significance: "Recognized as the crucial evolutionary laboratory of Indian temple architecture, where Northern and Southern styles were built side-by-side.",
    keyFeatures: [
      "Four monumental rock-cut cave temples excavated into Badami's sheer red sandstone bluffs",
      "Cave 1's eighteen-armed Dancing Shiva (Nataraja) exhibiting 81 distinct Bharatanatyam mudras",
      "Pattadakal's Virupaksha and Mallikarjuna temples exemplifying Dravidian design maturity",
      "Papanatha Temple illustrating early experiments blending Northern Nagara spires with Southern mandapas"
    ],
    didYouKnow: "The Agastya Lake at Badami is framed by red sandstone cliffs and the 7th-century Bhutanatha temples, creating one of India's most dramatic landscape compositions.",
    artTrails: ["temple"]
  },
  {
    id: "belur-halebidu",
    name: "Belur & Halebidu",
    state: "Karnataka",
    region: "South",
    locationType: "monument",
    coordinates: { lat: 13.1623, lng: 75.8596 },
    hierarchy: "secondary",
    artForms: ["Architecture", "Sculpture"],
    era: "Medieval",
    tradition: "Hoysala Chloritic Schist Micro-Sculpture",
    period: "12th – 13th century CE",
    image: "assets/images/chola-nataraja-bronze.jpg",
    thumb: "assets/images/chola-nataraja-bronze.jpg",
    imageCredit: "Archaeological Survey of India / UNESCO World Heritage Centre (2023)",
    shortDescription: "Masterpieces of Hoysala sacred architecture, famous for star-shaped plinths, lathe-turned stone pillars, and astonishingly dense soapstone carving.",
    historicalContext: "Commissioned by Hoysala monarchs King Vishnuvardhana and King Narasimha I. Inscribed with the signed names of master sculptors such as Ruvari Mallitamma and Dasoja.",
    significance: "Designated a UNESCO World Heritage Site in 2023, representing the absolute zenith of microscopic soapstone deep-undercut bas-relief sculpture in world history.",
    keyFeatures: [
      "Star-shaped (stellate) raised platforms providing elongated perimeter walls for sculpture",
      "Intricately undercut chloritic schist (soapstone) that carves like butter and hardens with age",
      "Over 38 celebrated bracket figures of Shilabalikas (celestial maidens) wearing miniature jewelry",
      "Continuous base friezes of thousands of elephants, lions, horses, and floral creepers—no two identical"
    ],
    didYouKnow: "Hoysala sculptors were among the earliest in India to sign their stone panels with pride, etching their names, guild titles, and hometowns onto the temple walls.",
    artTrails: ["temple"]
  },
  {
    id: "lepakshi",
    name: "Lepakshi (Veerabhadra Temple)",
    state: "Andhra Pradesh",
    region: "South",
    locationType: "monument",
    coordinates: { lat: 13.8042, lng: 77.6074 },
    hierarchy: "secondary",
    artForms: ["Painting", "Architecture", "Sculpture"],
    era: "Early Modern",
    tradition: "Vijayanagara Ceiling Murals & Stone Sculptures",
    period: "c. 1530 – 1540 CE",
    image: "assets/images/chola-nataraja-bronze.jpg",
    thumb: "assets/images/chola-nataraja-bronze.jpg",
    imageCredit: "Archaeological Survey of India / Andhra Pradesh Tourism",
    shortDescription: "Spectacular 16th-century temple complex famed for its gravity-defying Hanging Pillar, colossal monolithic Nandi bull, and India's finest Vijayanagara ceiling frescoes.",
    historicalContext: "Built by brothers Virupanna and Veeranna, governors under Vijayanagara Emperor Achyuta Deva Raya, atop the tortoise-shaped hillock of Kurmasaila.",
    significance: "Holds the largest and best-preserved ceiling mural fresco in Asia, depicting the 14 incarnations of Shiva in vivid black-and-ochre contours.",
    keyFeatures: [
      "Legendary 'Hanging Pillar': an intricately carved granite column that does not touch the floor",
      "India's largest monolithic Nandi Bull (27 feet long, 15 feet high), carved out of a single granite hill",
      "Magnificent Natya Mandapa (dance hall) with life-size sculpted gods, musicians, and celestial dancers",
      "Seven-hooded Nagalinga canopy shielding a black granite Shiva lingam"
    ],
    didYouKnow: "You can pass a thin cloth or sheet of paper completely under the base of the famous Hanging Pillar, proving it is suspended without resting on the ground.",
    artTrails: ["temple", "painting"]
  },
  {
    id: "kalamkari-region",
    name: "Srikalahasti & Machilipatnam",
    state: "Andhra Pradesh",
    region: "South",
    locationType: "region",
    coordinates: { lat: 13.7498, lng: 79.6984 },
    hierarchy: "secondary",
    artForms: ["Painting", "Folk & Tribal"],
    era: "Early Modern",
    tradition: "Traditional Kalamkari Hand-Painted Cotton",
    period: "Medieval to Living Heritage",
    image: "assets/images/tanjore-gold-leaf-painting.jpg",
    thumb: "assets/images/tanjore-gold-leaf-painting.jpg",
    imageCredit: "Crafts Council of Andhra Pradesh / Ministry of Textiles",
    shortDescription: "The twin cradles of Kalamkari art: Srikalahasti's freehand bamboo pen sacred scrolls and Machilipatnam's natural vegetable dye block-printed textiles.",
    historicalContext: "Flourished under the Golconda Sultanate and Vijayanagara court. Traditional temple bards hung large painted cotton cloths behind narrative storytelling performances.",
    significance: "An ancient textile art using only organic plant and mineral mordants (myrobalan, alum, madder root) with zero chemical additives.",
    keyFeatures: [
      "Freehand drawing using a specialized tamarind bamboo reed pen (Kalam) wrapped in sheep's wool",
      "Treatment with buffalo milk and myrobalan nut wash to bond natural dyes with organic cotton fibers",
      "Elaborate Ramayana and Mahabharata narrative panels with Telugu poetic calligraphy",
      "Natural red dyes extracted from Indian madder root (chayroot) and rich indigos"
    ],
    didYouKnow: "In the 17th century, European maritime trade companies shipped millions of yards of Machilipatnam Kalamkari (known as 'Chintz') to Europe, sparking a major textile fashion craze.",
    artTrails: ["painting", "folk"]
  },
  {
    id: "kerala-murals",
    name: "Mattancherry & Padmanabhapuram",
    state: "Kerala",
    region: "South",
    locationType: "monument",
    coordinates: { lat: 9.9576, lng: 76.2598 },
    hierarchy: "secondary",
    artForms: ["Painting"],
    era: "Early Modern",
    tradition: "Kerala Classical Temple & Palace Murals",
    period: "16th – 18th century CE",
    image: "assets/images/raja-ravi-varma-shakuntala.jpg",
    thumb: "assets/images/raja-ravi-varma-shakuntala.jpg",
    imageCredit: "Archaeological Survey of India / Kerala State Archaeology Department",
    shortDescription: "Monumental temple and palace murals executed in warm saffron and ochre pigments, famed for voluptuous anatomical modeling and rhythmic flowing contours.",
    historicalContext: "Adorned the royal chambers of Mattancherry Dutch Palace in Kochi and the Travancore royal palace at Padmanabhapuram. Guided by traditional Sanskrit iconographic treatises like the Tantrasamucchaya.",
    significance: "The southern climax of classical Indian fresco painting, combining Ajanta-like contour shading with vibrant Kathakali-like theatrical expressions.",
    keyFeatures: [
      "Strict natural Panchavarna (five-color) system: red, yellow, green, black, and white",
      "Voluptuous figures with graceful lotus-shaped eyes, arched brows, and jeweled headdresses",
      "Famous 300-square-foot Ramayana mural cycle in the royal bedchamber of Mattancherry Palace",
      "Plaster grounds prepared from sea shell lime, tender coconut water, and plant gums"
    ],
    didYouKnow: "Kerala mural masters only used brushes crafted from the soft tail-tip hairs of domestic calves and the fine quills of arrowroot grass.",
    artTrails: ["painting"]
  },

  // =========================================================================
  // NORTHERN INDIA
  // =========================================================================
  {
    id: "sarnath",
    name: "Sarnath Deer Park",
    state: "Uttar Pradesh",
    region: "North",
    locationType: "site",
    coordinates: { lat: 25.3811, lng: 83.0214 },
    hierarchy: "major",
    artForms: ["Sculpture", "Architecture"],
    era: "Ancient",
    tradition: "Mauryan Pillars & Classical Gupta Sarnath School",
    period: "3rd century BCE – 5th century CE",
    image: "assets/images/lion-capital-sarnath.jpg",
    thumb: "assets/images/lion-capital-sarnath.jpg",
    imageCredit: "Sarnath Archaeological Museum (ASI)",
    shortDescription: "The sacred Deer Park where Gautama Buddha delivered his first sermon, yielding the official National State Emblem of India and the supreme Gupta Teaching Buddha.",
    historicalContext: "Emperor Ashoka erected the monumental Lion Capital here in 250 BCE. Seven centuries later under the Gupta Golden Age, Sarnath master sculptors achieved classical artistic perfection.",
    significance: "The intellectual epicenter of classical Indian stone sculpture, celebrated for glass-like Chunar sandstone polishing and spiritual serenity.",
    keyFeatures: [
      "Four back-to-back Asiatic Lions on the Ashoka Capital, adopted as the State Emblem of India",
      "The 24-spoked Dharma Chakra representing universal cosmic order, placed on India’s National Flag",
      "The 5th-century Gupta Teaching Buddha carved with translucent cling drapery and sublime equanimity",
      "Colossal Dhamek Stupa rising 143 feet into the sacred skyline of Sarnath"
    ],
    didYouKnow: "The legendary mirror-like 'Mauryan polish' on the Sarnath Lion Capital has resisted weathering, monsoons, and dust for over 2,250 years without losing its vitreous shine.",
    artTrails: ["buddhist"]
  },
  {
    id: "mathura",
    name: "Mathura",
    state: "Uttar Pradesh",
    region: "North",
    locationType: "city",
    coordinates: { lat: 27.4924, lng: 77.6737 },
    hierarchy: "secondary",
    artForms: ["Sculpture"],
    era: "Ancient",
    tradition: "Indigenous Mathura Kushan Sandstone Sculpture",
    period: "2nd century BCE – 4th century CE",
    image: "assets/images/mathura-kushan-sculpture.jpg",
    thumb: "assets/images/mathura-kushan-sculpture.jpg",
    imageCredit: "Government Museum, Mathura / Archaeological Survey of India",
    shortDescription: "The premier sculptural powerhouse of ancient North India, known for tactile, prana-filled sculptures carved from mottled red-spotted Sikri sandstone.",
    historicalContext: "Flourished along the Uttarapatha trade crossroads under the Kushan Empire. Mathura sculptors simultaneously created the first human images of Buddha, Hindu deities (Vishnu, Shiva, Durga), and Jain Tirthankaras.",
    significance: "Pioneered indigenous Indic anthropomorphic figurative sculpture, characterized by broad athletic shoulders, warm smiling countenances, and swelling inner yogic breath.",
    keyFeatures: [
      "Carved from iconic red-spotted sandstone quarried near Rupbas and Sikri",
      "Swelling thoracic forms expressing the spiritual retention of sacred breath (prana)",
      "Translucent muslin drapery clinging to the torso with delicate gathered shoulder folds",
      "Sensuous Yakshi rail bracket figures carved in joyful postures of nature veneration"
    ],
    didYouKnow: "The Mathura workshops were so celebrated that ready-carved statues were exported hundreds of miles across ancient India as far as Taxila, Sarnath, and Bengal.",
    artTrails: ["buddhist", "temple"]
  },
  {
    id: "kangra-valley",
    name: "Kangra Valley",
    state: "Himachal Pradesh",
    region: "North",
    locationType: "region",
    coordinates: { lat: 32.0998, lng: 76.2691 },
    hierarchy: "major",
    artForms: ["Painting", "Miniature"],
    era: "Early Modern",
    tradition: "Pahari Lyrical Miniature Painting",
    period: "c. 1775 – 1820 CE",
    image: "assets/images/kangra-gita-govinda.jpg",
    thumb: "assets/images/kangra-gita-govinda.jpg",
    imageCredit: "National Museum, New Delhi / Chandigarh Museum",
    shortDescription: "The verdant Himalayan valley where the romantic Pahari miniature school flourished under Raja Sansar Chand, illustrating Jayadeva's Gita Govinda.",
    historicalContext: "When Mughal ateliers dispersed in the 18th century, master artists of Pandit Seu's family (Nainsukh and Manaku) found enlightened sanctuary in the tranquil hills of Kangra.",
    significance: "Celebrated globally for lyricism, pastoral naturalism, rhythmic lines, and tender human emotions set against Himalayan mountain vistas.",
    keyFeatures: [
      "Lush, blooming Shivalik forest backdrops with meandering hill streams and flowering bowers",
      "Delicate female profiles drawn with pure lyrical line work and expressive emotional modesty",
      "Soft, cool pastel color orchestration: gentle sage greens, twilight mauves, and warm saffron robes",
      "Visual translation of Jayadeva's Sanskrit erotic-mystical poem, the Gita Govinda"
    ],
    didYouKnow: "Art historian Ananda Coomaraswamy famously wrote: 'What Chinese art achieved for landscape, Pahari painting achieved for human love.'",
    artTrails: ["painting"]
  },
  {
    id: "delhi-heritage",
    name: "Delhi (Imperial & National Studios)",
    state: "Delhi",
    region: "North",
    locationType: "city",
    coordinates: { lat: 28.6139, lng: 77.2090 },
    hierarchy: "major",
    artForms: ["Architecture", "Painting", "Modern"],
    era: "Early Modern",
    tradition: "Indo-Islamic Monuments & National Modernist Collections",
    period: "12th century CE to Contemporary Era",
    image: "assets/images/mughal-miniature-painting.jpg",
    thumb: "assets/images/mughal-miniature-painting.jpg",
    imageCredit: "Archaeological Survey of India / National Gallery of Modern Art (NGMA)",
    shortDescription: "The historic capital bridging Mughal imperial manuscript ateliers, soaring red sandstone monuments (Qutb Minar, Humayun's Tomb), and national modern art collections.",
    historicalContext: "Capital of successive sultanates and the Mughal Empire under Akbar, Jahangir, and Shah Jahan. Today home to the National Gallery of Modern Art (NGMA) and National Museum.",
    significance: "The political and artistic nerve center connecting centuries of courtly synthesis to post-independence modern Indian avant-garde art.",
    keyFeatures: [
      "Humayun’s Tomb: red sandstone and white marble charbagh garden tomb that inspired the Taj Mahal",
      "Qutb Minar: soaring 73-meter fluted sandstone minaret with calligraphic Quranic bands",
      "Imperial Kitabkhana manuscript ateliers producing the monumental Hamzanama and Akbarnama folios",
      "NGMA collections enshrining modern national treasures: Raja Ravi Varma, Amrita Sher-Gil, S.H. Raza"
    ],
    didYouKnow: "Humayun's Tomb was the first garden-tomb on the Indian subcontinent and introduced the monumental double dome to South Asian architecture.",
    artTrails: ["painting"]
  }
];

export const ART_TRAILS = [
  {
    id: "temple",
    name: "Temple Architecture Trail",
    subtitle: "Stone spires, rock monoliths & sacred mandapas",
    description: "From the monolithic top-down excavation of Ellora and Pallava shore reliefs to the soaring Nagara towers of Khajuraho and Chola granite vimanas.",
    locationIds: [
      "ellora-kailasa",
      "khajuraho-monuments",
      "konark-temple",
      "bhubaneswar",
      "mamallapuram",
      "thanjavur",
      "madurai",
      "hampi-vijayanagara",
      "badami-pattadakal",
      "belur-halebidu"
    ]
  },
  {
    id: "folk",
    name: "Living Folk & Tribal Trail",
    subtitle: "Indigenous symbols, mud murals & sacred crafts",
    description: "Explore living vernacular traditions where art is woven into village life—from Warli geometric dances and Gond mythic trees to Mithila ceremonial walls and Bastar metallurgy.",
    locationIds: [
      "warli-region",
      "gond-region",
      "bastar-region",
      "mithila-madhubani",
      "raghurajpur-puri",
      "kalamkari-region",
      "bishnupur-terracotta"
    ]
  },
  {
    id: "buddhist",
    name: "Buddhist Heritage Trail",
    subtitle: "Sacred caves, stupas & the enlightened path",
    description: "Follow the sacred footsteps of early Buddhism from the Ashokan pillars of Sarnath and Sanchi's torana gateways to Ajanta's celestial murals and Nalanda's monastic university.",
    locationIds: [
      "sarnath",
      "sanchi-stupa",
      "ajanta-caves",
      "nalanda",
      "bhimbetka-caves",
      "mathura"
    ]
  },
  {
    id: "painting",
    name: "Indian Painting Masters Trail",
    subtitle: "Ancient frescoes, court miniatures & modern wash",
    description: "Journey through thousands of years of painting—from Ajanta's Bodhisattva murals and Kishangarh's Bani Thani to Kangra romances, Tanjore gold foil, and Bengal School modernity.",
    locationIds: [
      "ajanta-caves",
      "delhi-heritage",
      "kishangarh-jaipur",
      "nathdwara",
      "kangra-valley",
      "thanjavur",
      "kalamkari-region",
      "kerala-murals",
      "kolkata-santiniketan"
    ]
  }
];

export const ART_FORMS_LIST = [
  "All",
  "Painting",
  "Sculpture",
  "Architecture",
  "Miniature",
  "Folk & Tribal",
  "Modern"
];

export const ERAS_LIST = [
  "All",
  "Ancient",
  "Classical",
  "Medieval",
  "Early Modern",
  "Modern",
  "Contemporary"
];

export const REGIONS_LIST = [
  "All",
  "North",
  "South",
  "East",
  "West",
  "Central"
];
