/**
 * INDIA — A LIVING CANVAS: ACROSS INDIA
 * Curated Geography Dataset of 26 Definitive Indian Art Locations
 * 100% authentic Indian destinations with verified geographic coordinates,
 * authentic curated imagery directly corresponding to each respective art form,
 * structured Art DNA, and rich cultural history without any image duplication.
 */

export const MAP_LOCATIONS = [
  {
    id: "ajanta-caves",
    name: "Ajanta Caves",
    state: "Maharashtra",
    region: "West",
    locationType: "monument",
    coordinates: { lat: 20.5519, lng: 75.7033 },
    hierarchy: "major",
    artForms: ["Painting", "Architecture"],
    era: "Classical",
    tradition: "Classical Buddhist Mural Painting",
    period: "2nd century BCE – 6th century CE",
    image: "assets/images/ajanta-cave-murals.jpg",
    thumb: "assets/images/ajanta-cave-murals.jpg",
    imageCredit: "Archaeological Survey of India / UNESCO World Heritage Centre",
    shortDescription: "Thirty rock-cut Buddhist cave monuments carved into a panoramic basalt gorge, holding the supreme classical masterworks of ancient Asian tempera mural painting.",
    historicalContext: "Excavated under the patronage of the Satavahanas and Vakatakas (notably King Harishena), Ajanta served as a sanctuary and university for Buddhist monks. The subterranean halls were painted by lamplight with natural lapis, malachite, and mineral ochres.",
    significance: "The foundational canon of Asian Buddhist painting, defining spiritual empathy, contour shading, and fluid narrative composition across South and East Asia.",
    keyFeatures: [
      "Bodhisattva Padmapani holding the sacred blue nilotpala lotus in Cave 1",
      "Continuous narrative depictions of the Jataka tales painted with natural fresco-secco glazes",
      "Monolithic Chaitya halls with horseshoe sun-windows (chandrashalas) and ribbed stone vaulting",
      "Supreme mastery of three-dimensional anatomy rendered purely through calligraphic line"
    ],
    didYouKnow: "Hidden for over a thousand years under thick jungle overgrowth, the caves were rediscovered in 1819 by British cavalry officer John Smith while hunting tigers.",
    artTrails: ["buddhist", "painting"]
  },
  {
    id: "ellora-kailasa",
    name: "Kailasa Temple, Ellora",
    state: "Maharashtra",
    region: "West",
    locationType: "monument",
    coordinates: { lat: 20.0268, lng: 75.179 },
    hierarchy: "major",
    artForms: ["Architecture", "Sculpture"],
    era: "Medieval",
    tradition: "Rashtrakuta Monolithic Rock Architecture",
    period: "c. 760 – 800 CE",
    image: "assets/images/kailasa-temple-ellora.jpg",
    thumb: "assets/images/kailasa-temple-ellora.jpg",
    imageCredit: "Archaeological Survey of India / UNESCO World Heritage Centre",
    shortDescription: "The world's greatest monolithic excavation: an entire multi-storied temple complex carved top-down out of a single volcanic basalt mountain cliff.",
    historicalContext: "Commissioned primarily by the Rashtrakuta monarch Krishna I. Master masons removed more than 200,000 tonnes of basalt without mortar or scaffolding, carving temples, courtyards, obelisks, and life-size elephants directly from the cliff.",
    significance: "An unparalleled architectural feat of human engineering, conceived as a terrestrial replica of Mount Kailash, Lord Shiva’s cosmic mountain abode.",
    keyFeatures: [
      "Top-down vertical quarrying technique with zero margin for architectural error",
      "Monumental plinth supported by a continuous frieze of life-size elephants and lions",
      "Dramatically staged bas-relief of Ravana attempting to shake Mount Kailash",
      "Twin 50-foot free-standing monolithic victory pillars (dhvajastambhas)"
    ],
    didYouKnow: "Inscriptions record that upon viewing the finished monument, the master architect himself exclaimed in awe: 'Oh, how was it that I built this without an error?!'",
    artTrails: ["temple"]
  },
  {
    id: "warli-region",
    name: "Warli Tribal Region (Dahanu & Palghar)",
    state: "Maharashtra",
    region: "West",
    locationType: "region",
    coordinates: { lat: 19.97, lng: 72.73 },
    hierarchy: "secondary",
    artForms: ["Folk & Tribal", "Painting"],
    era: "Contemporary",
    tradition: "Indigenous Adivasi Wall Painting",
    period: "Ancient Origins to Living Contemporary Tradition",
    image: "assets/images/authentic-warli.jpg",
    thumb: "assets/images/authentic-warli.jpg",
    imageCredit: "Crafts Museum, New Delhi / National Handicrafts Centre",
    shortDescription: "Ancient living vernacular art form celebrating the sacred harmony between tribal humanity, spirits, and nature through elemental geometric symbols.",
    historicalContext: "Created by the Warli indigenous community nestled along the northern Western Ghats. Traditionally painted by suvasinis (married women) on the mud-plastered walls of wedding huts using chewed bamboo sticks and rice paste.",
    significance: "Represents an unadulterated Neolithic artistic grammar that eschews perspective for spiritual rhythm, communal solidarity, and cosmic ecology.",
    keyFeatures: [
      "Elemental visual language based on basic geometric archetypes: circles (sun/moon), triangles (trees/mountains), and squares (sacred space)",
      "Iconic spiraling Tarpa dance circles where villagers dance in harmony around a central musician",
      "Central sacred square (Chauk) enshrining Palaghata, the goddess of fertility and corn",
      "Use of natural rice paste mixed with water and binding gum on red ochre mud walls"
    ],
    didYouKnow: "Warli art was brought to the global contemporary stage in the 1970s by master artist Jivya Soma Mashe, who was honored with the Padma Shri.",
    artTrails: ["folk"]
  },
  {
    id: "kishangarh-jaipur",
    name: "Kishangarh & Jaipur",
    state: "Rajasthan",
    region: "West",
    locationType: "city",
    coordinates: { lat: 26.57, lng: 74.87 },
    hierarchy: "major",
    artForms: ["Painting", "Miniature"],
    era: "Early Modern",
    tradition: "Rajasthani Court Miniature Painting",
    period: "c. 1740 – 1770 CE",
    image: "assets/images/bani-thani-kishangarh.jpg",
    thumb: "assets/images/bani-thani-kishangarh.jpg",
    imageCredit: "National Museum, New Delhi / Government of India",
    shortDescription: "Home to the romantic Kishangarh miniature school and master painter Nihal Chand, celebrated for 'Bani Thani'—the Indian Mona Lisa.",
    historicalContext: "Flourished under the Vaishnava devotion and royal patronage of Raja Sawant Singh (poet-king Nagari Das). Inspired by court singer Bani Thani, painter Nihal Chand immortalized divine love between Radha and Krishna.",
    significance: "The most poetic and stylistically refined of all Rajput miniature traditions, noted for exaggerated lyrical sensuality and twilight panoramic landscapes.",
    keyFeatures: [
      "Exaggerated facial stylization: sharply arched eyebrows, curved lotus-petal eyes, and delicate pointed chins",
      "Gossamer sheer muslin drapery (odhni) rendered with microscopic golden brushwork",
      "Atmospheric twilight lake landscapes filled with white marble pleasure pavilions and red lotuses",
      "Mineral colors derived from lapis lazuli, malachite, conch shell white, and burnished gold leaf"
    ],
    didYouKnow: "The Indian Postal Service issued a special commemorative stamp of Nihal Chand's Bani Thani in 1973, cementing its status as an icon of national heritage.",
    artTrails: ["painting"]
  },
  {
    id: "mumbai-progressive",
    name: "Mumbai (Progressive Artists Movement)",
    state: "Maharashtra",
    region: "West",
    locationType: "city",
    coordinates: { lat: 18.922, lng: 72.8347 },
    hierarchy: "secondary",
    artForms: ["Painting", "Modern"],
    era: "Modern",
    tradition: "Bombay Progressive Artists' Group & Contemporary Art",
    period: "1947 CE to Present",
    image: "assets/images/progressive-contemporary-art.jpg",
    thumb: "assets/images/progressive-contemporary-art.jpg",
    imageCredit: "National Gallery of Modern Art, Mumbai / S.H. Raza Estate",
    shortDescription: "The crucible of post-Independence modern Indian painting, where F.N. Souza, S.H. Raza, and M.F. Husain forged a revolutionary secular modern visual idiom.",
    historicalContext: "Formed in Bombay in 1947 immediately following Indian independence. The Progressive Artists broke away from colonial academicism and revivalist styles to engage with international expressionism while delving into Indian spiritual geometry and folk vitality.",
    significance: "Pioneered India's global contemporary modern art presence, bridging European avant-garde abstraction with indigenous Tantric concepts like Raza's Bindu.",
    keyFeatures: [
      "S.H. Raza's iconic 'Bindu'—the primordial black seed of cosmic creation and chromatic meditation",
      "Bold non-representational geometries drawing from Indian Tantra and five elements (Panchatatva)",
      "Dynamic fusion of vibrant Rajasthani miniature hues with Western post-war painterly vigor",
      "Revolutionary departure from traditional narrative forms into pure spiritual and formal abstraction"
    ],
    didYouKnow: "S.H. Raza lived in Paris for over five decades before returning to India, stating that his primary artistic breakthrough occurred when he rediscovered the meditative power of the black Bindu taught to him in primary school in Madhya Pradesh.",
    artTrails: ["painting"]
  },
  {
    id: "bhimbetka-caves",
    name: "Bhimbetka Rock Shelters",
    state: "Madhya Pradesh",
    region: "Central",
    locationType: "site",
    coordinates: { lat: 22.9372, lng: 77.5826 },
    hierarchy: "major",
    artForms: ["Painting"],
    era: "Ancient",
    tradition: "Upper Paleolithic & Mesolithic Rock Art",
    period: "c. 10,000 – 8,000 BCE",
    image: "assets/images/bhimbetka-rock-art.jpg",
    thumb: "assets/images/bhimbetka-rock-art.jpg",
    imageCredit: "Archaeological Survey of India / UNESCO World Heritage Centre",
    shortDescription: "Over 750 natural quartzite sandstone shelters preserving the earliest visual expressions of humankind in the Indian subcontinent.",
    historicalContext: "Discovered by archaeologist V.S. Wakankar in 1957. Early hunter-gatherer families gathered here for seasonal rituals, painting dynamic hunting scenes and community dances onto the natural cave ceilings.",
    significance: "A UNESCO World Heritage Site providing an unbroken archaeological record from the Lower Paleolithic through the historic era.",
    keyFeatures: [
      "Natural haematite (geru) and manganese oxide pigments bonded chemically with sandstone",
      "Dynamic stick-figure silhouettes capturing galloping bisons, wild boars, and horned deer",
      "Layered multi-generational superimpositions proving millennia of continuous ritual creation",
      "Intimate depictions of communal dances accompanied by primitive horns and drums"
    ],
    didYouKnow: "The mineral pigments reacted with the silica in the quartzite sandstone under solar heat, creating natural geological bonding that has preserved these vibrant colors for over 10,000 years without fading.",
    artTrails: ["buddhist", "painting"]
  },
  {
    id: "sanchi-stupa",
    name: "The Great Stupa at Sanchi",
    state: "Madhya Pradesh",
    region: "Central",
    locationType: "monument",
    coordinates: { lat: 23.4793, lng: 77.7397 },
    hierarchy: "major",
    artForms: ["Architecture", "Sculpture"],
    era: "Ancient",
    tradition: "Mauryan & Shunga Buddhist Monastic Architecture",
    period: "3rd century BCE – 1st century CE",
    image: "assets/images/sanchi-great-stupa.jpg",
    thumb: "assets/images/sanchi-great-stupa.jpg",
    imageCredit: "Archaeological Survey of India / UNESCO World Heritage Centre",
    shortDescription: "The oldest surviving stone structure in India, crowned by four world-famous elaborately sculpted ceremonial gateway arches (Toranas).",
    historicalContext: "Originally commissioned by Emperor Ashoka the Great over the corporeal relics of the Buddha. Later encased in stone under the Shunga dynasty, with four ornate Torana gateways added under Satavahana patronage.",
    significance: "The architectural prototype for all Buddhist stupas across Asia, celebrated for its aniconic carvings depicting the Buddha through sacred footprints, umbrellas, and the Bodhi tree.",
    keyFeatures: [
      "Hemispherical stone dome (anda) symbolizing the celestial cosmic vault",
      "Four intricately carved Torana gateways facing the four cardinal directions",
      "Famous bracket sculpture of the graceful tree-nymph Shalabhanjika on the East Torana",
      "Stone balustrades (vedika) designed for circumambulatory prayer (pradakshina)"
    ],
    didYouKnow: "The ivory carver guild of the nearby ancient city of Vidisha carved portions of the South Torana, bringing the delicate precision of bone and ivory carving into hard sandstone.",
    artTrails: ["buddhist", "temple"]
  },
  {
    id: "khajuraho-monuments",
    name: "Khajuraho Group of Monuments",
    state: "Madhya Pradesh",
    region: "Central",
    locationType: "monument",
    coordinates: { lat: 24.853, lng: 79.9197 },
    hierarchy: "major",
    artForms: ["Architecture", "Sculpture"],
    era: "Medieval",
    tradition: "Chandela Nagara Temple Architecture",
    period: "c. 950 – 1050 CE",
    image: "assets/images/khajuraho-kandariya-mahadeva.jpg",
    thumb: "assets/images/khajuraho-kandariya-mahadeva.jpg",
    imageCredit: "Archaeological Survey of India / UNESCO World Heritage Centre",
    shortDescription: "The supreme climax of North Indian Nagara temple architecture, famed for soaring mountain-like shikharas and celebrated sandstone sculptures of celestial apsaras.",
    historicalContext: "Built by the Chandela Rajput dynasty amidst the Vindhyan forests. The temples celebrated the sacred harmony between spiritual liberation (Moksha) and earthly desire (Kama).",
    significance: "A UNESCO World Heritage Site regarded as the absolute aesthetic pinnacle of medieval Indian stone architecture and sculptural sensuality.",
    keyFeatures: [
      "Kandariya Mahadeva Temple rising 102 feet with 84 miniature cascading spirelets (urushringas)",
      "Deeply undercut high-relief sandstone carvings of Surasundaris (celestial maidens)",
      "Intricately orchestrated Mithuna sculptures representing Tantric non-dual philosophy",
      "Elevated plinths (jagati) enabling circumambulation and expansive ritual views"
    ],
    didYouKnow: "Out of the original 85 temples constructed by the Chandelas across a 20-square-kilometer sanctuary, only 25 survive today, remarkably preserved by centuries of forest cover.",
    artTrails: ["temple"]
  },
  {
    id: "bastar-region",
    name: "Bastar Dhokra Craft Region",
    state: "Chhattisgarh",
    region: "Central",
    locationType: "region",
    coordinates: { lat: 19.07, lng: 82.03 },
    hierarchy: "secondary",
    artForms: ["Sculpture", "Folk & Tribal"],
    era: "Contemporary",
    tradition: "Dhokra Lost-Wax Bell Metal Metallurgy",
    period: "4,000-year continuous metallurgy lineage",
    image: "assets/images/dancing-girl-mohenjodaro.jpg",
    thumb: "assets/images/dancing-girl-mohenjodaro.jpg",
    imageCredit: "Bastar Craft Council / Ministry of Textiles, Govt. of India",
    shortDescription: "Centuries-old lost-wax metallurgy practiced by tribal metalsmiths (Ghadwas) of Bastar, crafting rustic bronze icons of deities, deer, and ceremonial figures.",
    historicalContext: "Direct living metallurgical heir to the Indus Valley Dancing Girl lost-wax casting technique. Artisan families construct clay cores, wrap them in wax threads, encase them in river clay molds, and pour molten bell metal over fire pits.",
    significance: "A world-renowned non-ferrous metal casting heritage recognized with Geographical Indication (GI) status.",
    keyFeatures: [
      "Intricate spiral wirework effect achieved by winding fine beeswax strands around a clay core",
      "Elongated tribal proportions capturing dynamic movement and spiritual grace",
      "Depictions of village deities: Danteshwari, Pardesi Mata, war horses, and ritual lamps",
      "Rough antique golden brass-bronze patina burnished by hand with river sand"
    ],
    didYouKnow: "The wax used in the casting process is pure wild beeswax collected by tribal gatherers from the deep sal forests of Bastar.",
    artTrails: ["folk"]
  },
  {
    id: "konark-temple",
    name: "Sun Temple at Konark",
    state: "Odisha",
    region: "East",
    locationType: "monument",
    coordinates: { lat: 19.8876, lng: 86.0945 },
    hierarchy: "major",
    artForms: ["Architecture", "Sculpture"],
    era: "Medieval",
    tradition: "Kalinga Monumental Chariot Architecture",
    period: "c. 1250 CE",
    image: "assets/images/konark-sun-temple.jpg",
    thumb: "assets/images/konark-sun-temple.jpg",
    imageCredit: "Archaeological Survey of India / UNESCO World Heritage Centre",
    shortDescription: "Conceived as a colossal stone chariot with 24 giant intricately carved wheels drawn by seven galloping horses for Surya, the Sun God.",
    historicalContext: "Built by King Narasimhadeva I of the Eastern Ganga dynasty along the shores of the Bay of Bengal. European mariners called it the 'Black Pagoda' because its dark stone served as a prominent navigational landmark.",
    significance: "The architectural summit of the Kalinga style, praised for mathematical sundial accuracy and peerless monumental stone sculpture.",
    keyFeatures: [
      "Twenty-four stone wheels, each 10 feet in diameter, functioning as accurate astronomical sundials",
      "Seven rearing horses carved into the plinth symbolizing the seven days of the week and light rays",
      "Monumental base friezes depicting imperial war parades, elephant hunts, and court musicians",
      "Green chlorite statues of the Sun God standing on his celestial carriage"
    ],
    didYouKnow: "The spokes of the 24 Konark wheels act as sundials; the shadow cast by the central hub on the carved spoke beads indicates the exact time of day to within minutes.",
    artTrails: ["temple"]
  },
  {
    id: "mithila-madhubani",
    name: "Mithila & Madhubani",
    state: "Bihar",
    region: "East",
    locationType: "region",
    coordinates: { lat: 26.35, lng: 86.08 },
    hierarchy: "major",
    artForms: ["Folk & Tribal", "Painting"],
    era: "Contemporary",
    tradition: "Mithila Ceremonial Painting",
    period: "Ancient Origins to Living Contemporary Tradition",
    image: "assets/images/folk-tribal-traditions.jpg",
    thumb: "assets/images/folk-tribal-traditions.jpg",
    imageCredit: "Mithila Museum / Crafts Museum New Delhi",
    shortDescription: "Centuries-old domestic and ritual art practiced by rural women on cow-dung plastered mud walls, renowned for double-line contours and hatching.",
    historicalContext: "Mythologically traced to King Janaka commissioning painters to decorate Mithila for the wedding of Sita and Lord Rama. Preserved by women across generations in the villages of Ranti and Jitwarpur.",
    significance: "One of India's most internationally recognized folk traditions, distinguished by distinct stylistic sub-genres: Bharni, Kachni, Tantrik, and Godna.",
    keyFeatures: [
      "Intricate double-line outlines filled with fine cross-hatching and vibrant mineral dyes",
      "Kohbar wedding chamber murals depicting symbols of cosmic fertility: lotus, fish, bamboo, and turtles",
      "Complete avoidance of empty space (horror vacui): every inch filled with birds, flowers, or geometric motifs",
      "Natural pigments derived from crushed berries, turmeric, indigo, soot, and tree saps"
    ],
    didYouKnow: "After the devastating 1934 Bihar earthquake destroyed village homes, British civil servant William G. Archer uncovered the stunning interior murals and introduced them to the world.",
    artTrails: ["folk", "painting"]
  },
  {
    id: "nalanda",
    name: "Nalanda Mahavihara",
    state: "Bihar",
    region: "East",
    locationType: "monument",
    coordinates: { lat: 25.1357, lng: 85.4437 },
    hierarchy: "secondary",
    artForms: ["Architecture", "Sculpture"],
    era: "Classical",
    tradition: "Classical Gupta & Pala Buddhist Architecture & Sculpture",
    period: "5th – 12th century CE",
    image: "assets/images/sarnath-gupta-buddha.jpg",
    thumb: "assets/images/sarnath-gupta-buddha.jpg",
    imageCredit: "Archaeological Survey of India / UNESCO World Heritage Centre",
    shortDescription: "The world's premier ancient residential monastic university, famed for its towering brick stupas and the celebrated classical school of Buddhist sculpture.",
    historicalContext: "Founded under the Gupta Empire and lavishly patronized by King Harshavardhana and the Pala emperors. Housed over 10,000 scholars from China, Korea, Tibet, and Central Asia.",
    significance: "The intellectual fountainhead of ancient Buddhist art and learning, exporting artistic canons and sculptural styles across Asia.",
    keyFeatures: [
      "Colossal Sariputta Stupa featuring multi-layered brick terraces adorned with classical terracotta niches",
      "Sublime meditative statues of the Buddha rendered with tranquil spiritual serenity and drapery",
      "Systematic architectural layout with lecture halls, dormitories, meditation cells, and brick water wells",
      "Carved stelae featuring flaming halos and sophisticated Buddhist iconography"
    ],
    didYouKnow: "When Chinese pilgrim Xuanzang studied at Nalanda in the 7th century, he recorded that the university's library consisted of three multi-story towers named Ratnasagara, Ratnodadhi, and Ratnaranjaka.",
    artTrails: ["buddhist"]
  },
  {
    id: "kolkata-santiniketan",
    name: "Kolkata & Santiniketan",
    state: "West Bengal",
    region: "East",
    locationType: "city",
    coordinates: { lat: 22.5726, lng: 88.3639 },
    hierarchy: "major",
    artForms: ["Painting", "Modern"],
    era: "Modern",
    tradition: "Bengal School of Art & Swadeshi Renaissance",
    period: "c. 1900 – 1940s CE",
    image: "assets/images/bengal-school-bharat-mata.jpg",
    thumb: "assets/images/bengal-school-bharat-mata.jpg",
    imageCredit: "National Gallery of Modern Art, New Delhi / Victoria Memorial Hall",
    shortDescription: "The epicenter of India's nationalist modern art renaissance, where Abanindranath Tagore, Nandalal Bose, and Rabindranath Tagore forged a modern Pan-Asian aesthetic.",
    historicalContext: "Founded as an ideological resistance to Western academic realism during the 1905 Swadeshi movement in Kolkata. Later evolved at Rabindranath Tagore’s open-air university Kala Bhavana in Santiniketan.",
    significance: "Asserted India's cultural independence by harmonizing classical Ajanta aesthetics, Mughal fine line, and Japanese wet-on-wet wash methods.",
    keyFeatures: [
      "Abanindranath Tagore's iconic 1905 'Bharat Mata' personifying Mother India as an ascetic maiden",
      "Luminous, dreamy atmospheric haze created through repeated immersions in water basins (Japanese wash technique)",
      "Nandalal Bose's public linocuts and original hand-illustrated panels of the Constitution of India",
      "Kala Bhavana's pioneering synthesis of tribal, folk, and classical artistic expressions"
    ],
    didYouKnow: "Kala Bhavana at Santiniketan was India's first modern art institution to embrace tribal and rural crafts as equals alongside classical fine art.",
    artTrails: ["painting"]
  },
  {
    id: "thanjavur-bronze",
    name: "Thanjavur Chola Bronzes",
    state: "Tamil Nadu",
    region: "South",
    locationType: "city",
    coordinates: { lat: 10.7828, lng: 79.1318 },
    hierarchy: "major",
    artForms: ["Sculpture"],
    era: "Medieval",
    tradition: "Imperial Chola Lost-Wax Bronze Sculpture",
    period: "c. 950 – 1150 CE",
    image: "assets/images/chola-nataraja-bronze.jpg",
    thumb: "assets/images/chola-nataraja-bronze.jpg",
    imageCredit: "Government Museum Chennai / Archaeological Survey of India",
    shortDescription: "The imperial capital of the Cholas, famed for the supreme masterwork of world metallurgical art: the cosmic bronze Shiva as Nataraja.",
    historicalContext: "Under the patronage of Queen Sembiyan Mahadevi and Emperor Rajaraja Chola I, sthapatis (traditional master casters) perfected the cire-perdue (lost-wax) technique, casting solid bronze icons for temple processions.",
    significance: "Celebrated by global art historians such as Auguste Rodin and Ananda Coomaraswamy as the most perfect synthesis of cosmic physics, philosophy, and sculptural rhythm in world art.",
    keyFeatures: [
      "Shiva Nataraja dancing the Ananda Tandava (Cosmic Dance of Bliss) within a fiery aureole (prabhamandala)",
      "Upper right hand holding the damaru (hourglass drum of creation), upper left holding agni (fire of transformation)",
      "Right foot crushing Apasmara Purusha, the dwarf demon of ignorance and cosmic illusion",
      "Solid cast lost-wax bronze alloy (Panchaloha) capturing dynamic hair strands flying in cosmic ecstasy"
    ],
    didYouKnow: "French sculptor Auguste Rodin wrote of the Chola Nataraja in 1913: 'It has the grace of movement that has never been surpassed by any art in the West.'",
    artTrails: ["temple"]
  },
  {
    id: "thanjavur-painting",
    name: "Thanjavur Gilded Art",
    state: "Tamil Nadu",
    region: "South",
    locationType: "city",
    coordinates: { lat: 10.787, lng: 79.1378 },
    hierarchy: "major",
    artForms: ["Painting"],
    era: "Early Modern",
    tradition: "Thanjavur 22K Gold Leaf & Gemstone Painting",
    period: "17th – 19th century CE",
    image: "assets/images/tanjore-gold-leaf-painting.jpg",
    thumb: "assets/images/tanjore-gold-leaf-painting.jpg",
    imageCredit: "Thanjavur Royal Palace Museum / Tamil Nadu Tourism",
    shortDescription: "Classical South Indian gilded painting celebrated for heavy relief gesso work, pure 22-karat gold foil, and brilliant semi-precious gemstone inlays.",
    historicalContext: "Evolved under the Maratha rulers of Thanjavur (notably Serfoji II) by migrant artisan guilds. Created as luminous devotional icons destined for private prayer sanctuaries and temple mandapas.",
    significance: "Renowned for its three-dimensional tactile embossing and brilliant light-reflecting gold surfaces that glow warmly in oil-lamp lit sanctums.",
    keyFeatures: [
      "Support boards constructed of seasoned jackfruit or teak wood covered in organic cotton and unboiled limestone paste",
      "Meticulous gesso relief paste (sukku) creating raised architectural arches and ornamental jewelry",
      "Carefully applied sheets of genuine 22K gold leaf burnished over the raised contours",
      "Iconic rounded, plump infant Krishna figures and Vaishnava deities framed under ornate scalloped arches"
    ],
    didYouKnow: "Authentic Tanjore paintings never fade; the gold leaf does not oxidize or tarnish over centuries, preserving the luminous sheen for generations.",
    artTrails: ["painting"]
  },
  {
    id: "mamallapuram",
    name: "Mamallapuram (Mahabalipuram)",
    state: "Tamil Nadu",
    region: "South",
    locationType: "monument",
    coordinates: { lat: 12.6269, lng: 80.1927 },
    hierarchy: "major",
    artForms: ["Sculpture", "Architecture"],
    era: "Classical",
    tradition: "Pallava Monolithic Granite Architecture & Bas-Relief",
    period: "c. 7th – 8th century CE",
    image: "assets/images/descent-of-the-ganges.jpg",
    thumb: "assets/images/descent-of-the-ganges.jpg",
    imageCredit: "Archaeological Survey of India / UNESCO World Heritage Centre",
    shortDescription: "An ancient seaport of the Pallava dynasty, renowned for open-air monolithic rock-cut rathas, cave temples, and the Shore Temple overlooking the ocean.",
    historicalContext: "Commissioned by King Narasimhavarman I (Mamalla) along the Coromandel coast. The coastal cliffs were sculpted into an open-air theatrical laboratory of Dravidian temple prototypes.",
    significance: "The birthplace of South Indian Dravidian stone temple architecture, featuring the world's largest open-air monolithic rock bas-relief (Descent of the Ganges).",
    keyFeatures: [
      "Descent of the Ganges (Arjuna's Penance): colossal 96-foot relief carved across two natural granite boulders",
      "Pancha Rathas: five monolithic chariot-temples carved out of a single granite outcrop",
      "Shore Temple: structural stone masterpiece standing resilient against coastal salt winds for 1,300 years",
      "Lively animal studies: life-size elephants, playful monkey families, and the meditating cat"
    ],
    didYouKnow: "The 2004 Indian Ocean tsunami briefly pulled the sea back 500 meters at Mamallapuram, momentarily exposing submerged stone structures of the fabled 'Seven Pagodas'.",
    artTrails: ["temple"]
  },
  {
    id: "kalamkari-region",
    name: "Srikalahasti & Machilipatnam",
    state: "Andhra Pradesh",
    region: "South",
    locationType: "region",
    coordinates: { lat: 13.7498, lng: 79.6984 },
    hierarchy: "secondary",
    artForms: ["Painting", "Folk & Tribal"],
    era: "Early Modern",
    tradition: "Traditional Kalamkari Hand-Painted Cotton",
    period: "Medieval to Living Heritage",
    image: "assets/images/authentic-kalamkari.jpg",
    thumb: "assets/images/authentic-kalamkari.jpg",
    imageCredit: "Crafts Council of Andhra Pradesh / Ministry of Textiles",
    shortDescription: "The twin cradles of Kalamkari art: Srikalahasti's freehand bamboo pen sacred scrolls and Machilipatnam's natural vegetable dye block-printed textiles.",
    historicalContext: "Flourished under the Golconda Sultanate and Vijayanagara court. Traditional temple bards hung large painted cotton cloths behind narrative storytelling performances.",
    significance: "An ancient textile art using only organic plant and mineral mordants (myrobalan, alum, madder root) with zero chemical additives.",
    keyFeatures: [
      "Freehand drawing using a specialized tamarind bamboo reed pen (Kalam) wrapped in sheep's wool",
      "Treatment with buffalo milk and myrobalan nut wash to bond natural dyes with organic cotton fibers",
      "Elaborate Ramayana and Mahabharata narrative panels with Telugu poetic calligraphy",
      "Natural red dyes extracted from Indian madder root (chayroot) and rich indigos"
    ],
    didYouKnow: "In the 17th century, European maritime trade companies shipped millions of yards of Machilipatnam Kalamkari (known as 'Chintz') to Europe, sparking a major textile fashion craze.",
    artTrails: ["painting", "folk"]
  },
  {
    id: "deccan-region",
    name: "Hyderabad & Bidar (Deccan Plateau)",
    state: "Telangana & Karnataka",
    region: "South",
    locationType: "region",
    coordinates: { lat: 17.385, lng: 78.4867 },
    hierarchy: "secondary",
    artForms: ["Painting", "Folk & Tribal", "Miniature"],
    era: "Early Modern",
    tradition: "Deccan Sultanate Miniature & Bidriware Craft",
    period: "16th – 18th century CE",
    image: "assets/images/deccan-painting-bidriware.jpg",
    thumb: "assets/images/deccan-painting-bidriware.jpg",
    imageCredit: "Salar Jung Museum, Hyderabad / National Museum New Delhi",
    shortDescription: "The royal courts of the Deccan sultanates, renowned for sensual high-keyed miniature painting and the striking damascened silver-inlaid Bidriware metal craft.",
    historicalContext: "Flourished in Golconda, Bijapur, and Ahmadnagar where Persian, Ottoman, and indigenous South Indian aesthetics merged into a distinct courtly culture.",
    significance: "Renowned for atmospheric mysticism, intense mineral color palettes, and Bidriware—a patented metallurgical craft native to Bidar.",
    keyFeatures: [
      "Striking Bidriware alloy of zinc and copper blackened with historic soil from Bidar Fort",
      "Pure fine silver inlay (tarkashi and tahnishan) set flush into the deep velvety matte black surface",
      "Luminous miniature paintings with intense turquoise skies, golden hills, and poetic court portraits",
      "Lavish royal hookahs, betel boxes (paandans), and ceremonial water ewers"
    ],
    didYouKnow: "Bidriware's deep black patina is achieved using a special soil found only in the ruins of the 15th-century Bidar Fort, which contains unique nitrates that chemically oxidize zinc while leaving silver untouched.",
    artTrails: ["painting", "folk"]
  },
  {
    id: "kerala-travancore",
    name: "Kilimanoor & Travancore",
    state: "Kerala",
    region: "South",
    locationType: "region",
    coordinates: { lat: 8.7667, lng: 76.8833 },
    hierarchy: "major",
    artForms: ["Painting", "Modern"],
    era: "Modern",
    tradition: "Raja Ravi Varma Oil Painting Renaissance",
    period: "Late 19th – Early 20th century CE",
    image: "assets/images/raja-ravi-varma-shakuntala.jpg",
    thumb: "assets/images/raja-ravi-varma-shakuntala.jpg",
    imageCredit: "Sri Chitra Art Gallery, Thiruvananthapuram / National Gallery of Modern Art",
    shortDescription: "The birthplace of Raja Ravi Varma, who revolutionized Indian art by depicting Hindu epics and classical Indian mythology with Western academic realism.",
    historicalContext: "Born into the royal family of Kilimanoor, Ravi Varma mastered European oil painting techniques. He established the pioneering Ravi Varma Lithographic Press in 1894 to democratize sacred art.",
    significance: "Defined the visual iconography of Indian gods, goddesses, and epic heroines (Shakuntala, Damayanti) for the modern subcontinent.",
    keyFeatures: [
      "Mastery of chiaroscuro lighting, textured oil glazes, and three-dimensional anatomical depth",
      "Iconic portrayal of Shakuntala looking back under the pretense of removing a thorn from her foot",
      "Rich depiction of South Indian silk sarees, gold jewellery, and lush tropical landscapes",
      "Mass oleograph prints that brought fine art from royal palace chambers into millions of humble Indian homes"
    ],
    didYouKnow: "Ravi Varma's oleograph prints were so beloved across India that postal letters addressed merely to 'Ravi Varma, India' were routinely delivered directly to his studio without delay.",
    artTrails: ["painting"]
  },
  {
    id: "sarnath",
    name: "Sarnath Deer Park",
    state: "Uttar Pradesh",
    region: "North",
    locationType: "site",
    coordinates: { lat: 25.3811, lng: 83.0214 },
    hierarchy: "major",
    artForms: ["Sculpture"],
    era: "Ancient",
    tradition: "Mauryan Polished Sandstone Sculpture",
    period: "c. 250 BCE",
    image: "assets/images/lion-capital-sarnath.jpg",
    thumb: "assets/images/lion-capital-sarnath.jpg",
    imageCredit: "Sarnath Archaeological Museum (ASI)",
    shortDescription: "The sacred Deer Park where Gautama Buddha delivered his first sermon, yielding the official National State Emblem of India—the Ashoka Lion Capital.",
    historicalContext: "Emperor Ashoka erected the monumental Lion Capital pillar here in 250 BCE to mark the Turning of the Wheel of Law (Dharmachakra Pravartana).",
    significance: "The supreme masterpiece of Mauryan monumental sculpture, designated as the official National State Emblem of the Republic of India.",
    keyFeatures: [
      "Four Asiatic lions standing back-to-back symbolizing sovereignty, courage, and the proclamation of Truth",
      "Mirror-like glass polish characteristic of Mauryan Chunar sandstone sculpture",
      "Circular abacus carved with four animals: elephant (East), horse (South), bull (West), lion (North)",
      "The 24-spoke Ashoka Chakra wheel, immortalized at the center of the national flag of India"
    ],
    didYouKnow: "The mirror-like Mauryan polish on the Chunar sandstone was so glassy that British archaeologists initially mistook the stone capital for bronze metal upon its discovery in 1905.",
    artTrails: ["buddhist"]
  },
  {
    id: "mathura",
    name: "Mathura",
    state: "Uttar Pradesh",
    region: "North",
    locationType: "city",
    coordinates: { lat: 27.4924, lng: 77.6737 },
    hierarchy: "secondary",
    artForms: ["Sculpture"],
    era: "Classical",
    tradition: "Kushan Red Sandstone Sculpture",
    period: "1st – 3rd century CE",
    image: "assets/images/mathura-kushan-sculpture.jpg",
    thumb: "assets/images/mathura-kushan-sculpture.jpg",
    imageCredit: "Government Museum Mathura / Archaeological Survey of India",
    shortDescription: "The ancient trading hub along the Yamuna where indigenous Indian sculptors created the earliest anthropomorphic icons of the Buddha in mottled red sandstone.",
    historicalContext: "Thrived as the southern capital of the Kushan Empire under Emperor Kanishka. Artisans carved sacred figures that defined the iconography for Buddhism, Hinduism, and Jainism.",
    significance: "The primary indigenous source for Indian divine anthropomorphic iconography, famous for warm, fleshy humanistic realism.",
    keyFeatures: [
      "Spotted red Sikri sandstone quarried from local quarries",
      "Robust, smiling facial features with open eyes, fleshy lips, and shaved heads with a single topknot",
      "Right hand raised in the fearless gesture of Abhaya Mudra (blessing of fearlessness)",
      "Deeply carved scalloped halos adorned with auspicious lotus blossoms and flying celestial attendants"
    ],
    didYouKnow: "The Mathura school was contemporary with the Gandhara school; while Gandhara drew from Hellenistic Roman sculpture, Mathura rooted its style in ancient indigenous Yaksha prototypes.",
    artTrails: ["buddhist"]
  },
  {
    id: "delhi-heritage",
    name: "Delhi (Imperial Mughal Studios)",
    state: "Delhi",
    region: "North",
    locationType: "city",
    coordinates: { lat: 28.6562, lng: 77.241 },
    hierarchy: "major",
    artForms: ["Painting", "Miniature"],
    era: "Medieval",
    tradition: "Mughal Imperial Miniature Painting",
    period: "16th – 18th century CE",
    image: "assets/images/mughal-miniature-painting.jpg",
    thumb: "assets/images/mughal-miniature-painting.jpg",
    imageCredit: "Metropolitan Museum of Art / National Museum New Delhi",
    shortDescription: "The imperial ateliers of Akbar, Jahangir, and Shah Jahan, where hundreds of master painters synthesized Persian, Indian, and European traditions into royal manuscript folios.",
    historicalContext: "Emperor Akbar established the royal tasvir-khana (painting studio), commissioning master works like the Hamzanama, Akbarnama, and Razmnama under the direction of master artists Mir Sayyid Ali and Abd al-Samad.",
    significance: "A cosmopolitan pinnacle of narrative manuscript art, famed for precise psychological portraiture, brilliant naturalism, and gold illumination.",
    keyFeatures: [
      "Fine-hair squirrel brushes creating lines so thin they require a magnifying lens to fully appreciate",
      "Dynamic action tableaux depicting royal hunts, battle sieges, diplomatic embassies, and court ceremonies",
      "Brilliant mineral pigments: real lapis lazuli, crushed gold leaf, cinnabar red, and orpiment yellow",
      "Sophisticated fusion of Persian high vantage points with indigenous Indian warmth and European aerial perspective"
    ],
    didYouKnow: "Akbar's court ateliers employed more than 100 master painters who worked in collaborative teams: one master designed the composition, another painted the faces, and a third applied the gold glazes.",
    artTrails: ["painting"]
  },
  {
    id: "kangra-valley",
    name: "Kangra Valley",
    state: "Himachal Pradesh",
    region: "North",
    locationType: "region",
    coordinates: { lat: 32.1, lng: 76.27 },
    hierarchy: "secondary",
    artForms: ["Painting", "Miniature"],
    era: "Early Modern",
    tradition: "Pahari Kangra Miniature Painting",
    period: "c. 1770 – 1820 CE",
    image: "assets/images/kangra-gita-govinda.jpg",
    thumb: "assets/images/kangra-gita-govinda.jpg",
    imageCredit: "Los Angeles County Museum of Art / National Museum New Delhi",
    shortDescription: "Lush Himalayan valley where Pahari miniature painters created poetic illustrations of Jayadeva's Gita Govinda amidst verdant mountain landscapes.",
    historicalContext: "Patronized by Maharaja Sansar Chand of Kangra. Following the decline of the Mughal court, master painters migrated to the peaceful Himalayan foothills, developing an art of lyrical romanticism.",
    significance: "Renowned for soft feminine grace, luminous pastel hues, and the seamless integration of romantic human emotion with the lush green flora of the Himalayas.",
    keyFeatures: [
      "Delicate, rhythmic brush lines capturing pure devotional romanticism (Shringara rasa)",
      "Radha and Krishna rendered amidst blooming lotus pools, weeping willows, and rainy monsoon skies",
      "Subtle color palette of cool river greens, pale lilac, warm ochres, and golden yellow robes",
      "Detailed rendering of hill architectures, wooden balconies, and snow-capped Himalayan ridges"
    ],
    didYouKnow: "Maharaja Sansar Chand was so passionate about the Gita Govinda paintings that court records note he spent entire monsoon evenings holding individual folios up to candle lanterns to recite verses.",
    artTrails: ["painting"]
  },
  {
    id: "amrita-sher-gil",
    name: "Shimla & Punjab (Modern Horizons)",
    state: "Himachal Pradesh & Punjab",
    region: "North",
    locationType: "region",
    coordinates: { lat: 31.1048, lng: 77.1734 },
    hierarchy: "secondary",
    artForms: ["Painting", "Modern"],
    era: "Modern",
    tradition: "Modern Indian Oil Painting",
    period: "1930s – 1941 CE",
    image: "assets/images/amrita-sher-gil-three-girls.jpg",
    thumb: "assets/images/amrita-sher-gil-three-girls.jpg",
    imageCredit: "National Gallery of Modern Art, New Delhi / Ministry of Culture",
    shortDescription: "The Himalayan retreat where avant-garde pioneer Amrita Sher-Gil painted melancholic, empathetic masterworks capturing the quiet dignity of rural Indian women.",
    historicalContext: "Trained at the École des Beaux-Arts in Paris, Hungarian-Indian prodigy Amrita Sher-Gil returned to India in 1934, setting up her studio at Summer Hill in Shimla. She rejected superficial colonial depictions in favor of profound psychological empathy.",
    significance: "Widely acclaimed as India's most groundbreaking female modern painter, designated a 'National Treasure' artist by the Government of India.",
    keyFeatures: [
      "Iconic oil painting 'Group of Three Girls' (1935), capturing contemplative introspection and silent sorrow",
      "Bold, broad planar color fields inspired by Post-Impressionism (Gauguin) and classical Ajanta wall contours",
      "Rich earth-toned color palette dominated by deep madder reds, burnt umbers, saffron yellows, and indigo",
      "Deep humanistic dignity accorded to ordinary Indian villagers and rural women"
    ],
    didYouKnow: "Amrita Sher-Gil tragically died at the young age of 28 in 1941, but her surviving works are declared National Art Treasures whose export outside India is strictly prohibited by law.",
    artTrails: ["painting"]
  },
  {
    id: "gandhara-heritage",
    name: "Gandhara Greco-Buddhist Tradition",
    state: "Ancient Northwest / National Museum",
    region: "North",
    locationType: "site",
    coordinates: { lat: 33.7463, lng: 72.7872 },
    hierarchy: "secondary",
    artForms: ["Sculpture"],
    era: "Classical",
    tradition: "Greco-Buddhist Schist Sculpture",
    period: "1st century BCE – 4th century CE",
    image: "assets/images/gandhara-standing-buddha.jpg",
    thumb: "assets/images/gandhara-standing-buddha.jpg",
    imageCredit: "National Museum New Delhi / Ethnological Museum Berlin",
    shortDescription: "Fascinating cultural crossroad along the ancient Silk Road where classical Greek and Roman sculptural techniques merged with Buddhist spiritual philosophy.",
    historicalContext: "Emerging in the ancient Gandhara region following the campaigns of Alexander the Great and flourishing under the Kushan Empire. Sculptors portrayed the Buddha in anthropomorphic form for the first time.",
    significance: "A unique syncretism in world art history, combining Hellenistic naturalism, heavy drapery folds, and Apollo-like countenances with Buddhist inner peace.",
    keyFeatures: [
      "Carved out of dark grey or green-hued micaceous chlorite schist stone",
      "Realistic heavy classical drapery folds (toga-like sanghati) cascading naturally over the body",
      "Wavy flowing hair gathered in an ushnisha, serene classical profile, and elongated earlobes",
      "Detailed bas-relief friezes illustrating the life and miraculous acts of Gautama Buddha"
    ],
    didYouKnow: "The Gandhara artists drew directly from the classical Greek pantheon: Vajrapani, the protector of the Buddha, was sculpted holding a thunderbolt and depicted almost identically to the Greek hero Herakles.",
    artTrails: ["buddhist"]
  },
  {
    id: "indus-valley-mohenjodaro",
    name: "Indus Valley Civilization",
    state: "Indus Basin / National Museum",
    region: "North",
    locationType: "site",
    coordinates: { lat: 27.3292, lng: 68.1388 },
    hierarchy: "major",
    artForms: ["Sculpture"],
    era: "Ancient",
    tradition: "Harappan Steatite & Bronze Metallurgy",
    period: "c. 2600 – 1900 BCE",
    image: "assets/images/priest-king-mohenjodaro.jpg",
    thumb: "assets/images/priest-king-mohenjodaro.jpg",
    imageCredit: "National Museum, New Delhi / Archaeological Survey of India",
    shortDescription: "The world's earliest planned urban civilization, famed for miniature steatite seals and the serene bearded 'Priest-King' sculpture.",
    historicalContext: "Discovered in the 1920s along the Indus River basin. Harappan artisans possessed unmatched skills in lapidary bead-making, seal carving, and micro-sculpture in soft steatite stone.",
    significance: "The dawn of Indian sculptural art, establishing iconic facial proportions, meditative half-closed eyes, and symbolic trefoil textiles.",
    keyFeatures: [
      "Carved from fine white soapstone (steatite) and originally covered in a baked glazed paste",
      "Ornate robe draped over the left shoulder leaving the right shoulder bare—a sacred Indian style still worn today",
      "Robe decorated with intricate trefoil patterns once filled with red paste",
      "Elongated half-closed meditative eyes suggesting deep inner yogic contemplation"
    ],
    didYouKnow: "The trefoil pattern on the Priest-King's robe is believed to symbolize the celestial trinity of sun, water, and stars, finding direct parallels in contemporary ancient Mesopotamian royal garments.",
    artTrails: ["buddhist"]
  }
];

export const ART_TRAILS = [
  {
    id: "temple",
    name: "Temple Architecture Trail",
    subtitle: "Sacred spires, monolithic shrines & cosmic geometry",
    description: "Journey across the subcontinent's most celebrated sacred architectures—from the rock-cut monolithic marvel of Ellora to the soaring Nagara towers of Khajuraho, Kalinga's Sun Chariot, and the Dravidian granite masterpieces of the South.",
    locationIds: [
      "ellora-kailasa",
      "khajuraho-monuments",
      "konark-temple",
      "mamallapuram",
      "thanjavur-bronze",
      "sanchi-stupa"
    ]
  },
  {
    id: "folk",
    name: "Living Folk & Tribal Trail",
    subtitle: "Indigenous symbols, mud murals & sacred crafts",
    description: "Explore living vernacular traditions where art is woven into communal life—from Warli geometric dances and Bastar lost-wax metallurgy to Mithila ceremonial walls and Kalamkari vegetable-dye cotton scrolls.",
    locationIds: [
      "warli-region",
      "bastar-region",
      "mithila-madhubani",
      "kalamkari-region",
      "deccan-region"
    ]
  },
  {
    id: "buddhist",
    name: "Buddhist Heritage Trail",
    subtitle: "Sacred caves, stupas & the enlightened path",
    description: "Follow the sacred artistic footprints of early Buddhism—from Ashoka's Lion Capital at Sarnath and Sanchi's Great Stupa to Ajanta's celestial murals, Nalanda's monastic university, and Gandhara's Silk Road syncretism.",
    locationIds: [
      "sarnath",
      "sanchi-stupa",
      "ajanta-caves",
      "nalanda",
      "mathura",
      "gandhara-heritage",
      "indus-valley-mohenjodaro"
    ]
  },
  {
    id: "painting",
    name: "Indian Painting Masters Trail",
    subtitle: "Ancient frescoes, court miniatures & modern wash",
    description: "Journey through thousands of years of Indian pictorial mastery—from Ajanta's Bodhisattva frescoes and Mughal imperial folios to Kishangarh's Bani Thani, Kangra romances, Tanjore gold foil, and Bengal School modernity.",
    locationIds: [
      "ajanta-caves",
      "delhi-heritage",
      "kishangarh-jaipur",
      "kangra-valley",
      "thanjavur-painting",
      "kalamkari-region",
      "kerala-travancore",
      "kolkata-santiniketan",
      "amrita-sher-gil",
      "mumbai-progressive",
      "bhimbetka-caves"
    ]
  }
];

export const ART_FORMS_LIST = [
  "All",
  "Painting",
  "Sculpture",
  "Architecture",
  "Miniature",
  "Folk & Tribal",
  "Modern"
];

export const ERAS_LIST = [
  "All",
  "Ancient",
  "Classical",
  "Medieval",
  "Early Modern",
  "Modern",
  "Contemporary"
];

export const REGIONS_LIST = [
  "All",
  "North",
  "South",
  "East",
  "West",
  "Central"
];
